package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"
)

type BlockProperty struct {
	Name      string   `json:"name"`
	Type      string   `json:"type"`
	NumValues int      `json:"num_values"`
	Values    []string `json:"values"`
}

type BlockDefinition struct {
	ID           uint16          `json:"id"`
	Name         string          `json:"name"`
	DefaultState uint16          `json:"defaultState"`
	MinState     uint16          `json:"minStateId"`
	MaxState     uint16          `json:"maxStateId"`
	Properties   []BlockProperty `json:"states"`
	BoundingBox  string          `json:"boundingBox"`
	EmitLight    uint8           `json:"emitLight"`
	FilterLight  uint8           `json:"filterLight"`
	Hardness     float32         `json:"hardness"`
	Diggable     bool            `json:"diggable"`
	HarvestTools map[string]bool `json:"harvestTools"`
	Drops        []uint16        `json:"drops"`
}

type ItemDefinition struct {
	ID   uint16 `json:"id"`
	Name string `json:"name"`
}

type LootTable struct {
	Type  string     `json:"type"`
	Pools []LootPool `json:"pools"`
}

type LootPool struct {
	BonusRolls float64         `json:"bonus_rolls"`
	Conditions []LootCondition `json:"conditions"`
	Entries    []LootEntry     `json:"entries"`
	Functions  []LootFunction  `json:"functions"`
	Rolls      float64         `json:"rolls"`
}

type LootEntry struct {
	Type       string          `json:"type"`
	Name       string          `json:"name"`
	Children   []LootEntry     `json:"children"`
	Conditions []LootCondition `json:"conditions"`
	Functions  []LootFunction  `json:"functions"`
	Weight     int             `json:"weight"`
	Quality    int             `json:"quality"`
}

type LootCondition struct {
	Block      string            `json:"block"`
	Condition  string            `json:"condition"`
	Entity     string            `json:"entity"`
	Predicate  LootItemPredicate `json:"predicate"`
	Properties map[string]string `json:"properties"`
	Term       json.RawMessage   `json:"term"`
}

type LootItemPredicate struct {
	Predicates map[string]json.RawMessage `json:"predicates"`
}

type LootEnchantmentRequirement struct {
	Enchantments string         `json:"enchantments"`
	Levels       LootLevelRange `json:"levels"`
}

type LootLevelRange struct {
	Min int `json:"min"`
}

type LootFunction struct {
	Count       json.RawMessage `json:"count"`
	Enchantment string          `json:"enchantment"`
	Formula     string          `json:"formula"`
	Function    string          `json:"function"`
	Conditions  []LootCondition `json:"conditions"`
}

type BlockDrop struct {
	Kind          string
	Item          string
	MinCount      int32
	MaxCount      int32
	Property      string
	Value         string
	CountProperty string
	Counts        []BlockDropCount
	RequiresActor bool
}

type BlockDropCount struct {
	Value string
	Count int32
}

type TagDefinition struct {
	Values []json.RawMessage `json:"values"`
}

type TagEntry struct {
	ID string `json:"id"`
}

type MiningTags struct {
	Traits map[string][]string
}

type MiningTagMapping struct {
	Name  string
	Value string
}

func main() {
	input := flag.String("input", "", "path to blocks.json")
	itemsPath := flag.String("items", "", "path to items.json")
	tagsPath := flag.String("tags", "", "path to canonical block tags")
	lootPath := flag.String("loot", "", "path to canonical block loot tables")
	output := flag.String("output", "", "generated Go output path")
	protocolOutput := flag.String("protocol-output", "", "generated protocol block tags output path")

	flag.Parse()

	if *input == "" || *itemsPath == "" || *tagsPath == "" || *lootPath == "" || *output == "" || *protocolOutput == "" {
		fmt.Fprintln(os.Stderr, "input, items, tags, loot, output and protocol-output are required")

		os.Exit(2)
	}

	raw, err := os.ReadFile(*input)
	if err != nil {
		fail(err)
	}

	var blocks []BlockDefinition

	err = json.Unmarshal(raw, &blocks)
	if err != nil {
		fail(err)
	}

	miningTags, err := readMiningTags(*tagsPath)
	if err != nil {
		fail(err)
	}

	itemIDs, err := readItemIDs(*itemsPath)
	if err != nil {
		fail(err)
	}

	drops, err := readBlockDrops(*lootPath, blocks, itemIDs)
	if err != nil {
		fail(err)
	}

	generated, err := generate(blocks, miningTags, drops)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*output, generated, 0o644)
	if err != nil {
		fail(err)
	}

	protocolTags, err := generateProtocolTags(blocks, *tagsPath)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*protocolOutput, protocolTags, 0o644)
	if err != nil {
		fail(err)
	}
}

func generateProtocolTags(blocks []BlockDefinition, root string) ([]byte, error) {
	blockIDs := make(map[string]uint16, len(blocks))

	for _, block := range blocks {
		blockIDs[block.Name] = block.ID
	}

	tagNames, err := blockTagNames(root)
	if err != nil {
		return nil, err
	}

	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-blocks; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package protocol")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var generatedBlockTags = []RegistryTag{")

	for _, tagName := range tagNames {
		values, err := expandTag(root, tagName, make(map[string]bool))
		if err != nil {
			return nil, err
		}

		entries := make([]int, 0, len(values))

		for blockName := range values {
			blockID, valid := blockIDs[blockName]
			if !valid {
				return nil, fmt.Errorf("block tag %s references unknown block %s", tagName, blockName)
			}

			entries = append(entries, int(blockID))
		}

		slices.Sort(entries)

		fmt.Fprintf(&output, "\t{ID: %q, Entries: []int32{", "minecraft:"+tagName)

		for _, entry := range entries {
			fmt.Fprintf(&output, "%d,", entry)
		}

		fmt.Fprintln(&output, "}},")
	}

	fmt.Fprintln(&output, "}")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated protocol tags: %w", err)
	}

	return formatted, nil
}

func blockTagNames(root string) ([]string, error) {
	var names []string

	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		if entry.IsDir() || filepath.Ext(path) != ".json" {
			return nil
		}

		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}

		name := strings.TrimSuffix(filepath.ToSlash(relative), ".json")
		names = append(names, name)

		return nil
	})

	if err != nil {
		return nil, fmt.Errorf("list block tags: %w", err)
	}

	slices.Sort(names)

	return names, nil
}

func generate(blocks []BlockDefinition, miningTags MiningTags, drops map[string]BlockDrop) ([]byte, error) {
	if len(blocks) == 0 {
		return nil, fmt.Errorf("block catalogue is empty")
	}

	for index, block := range blocks {
		if int(block.ID) != index {
			return nil, fmt.Errorf("block ID %d at index %d is not contiguous", block.ID, index)
		}

		if index > 0 && block.MinState != blocks[index-1].MaxState+1 {
			return nil, fmt.Errorf("state range for %s is not contiguous", block.Name)
		}
	}

	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-blocks; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package game")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "const MaxBlockID BlockID = %d\n", blocks[len(blocks)-1].ID)
	fmt.Fprintf(&output, "const MaxBlockState Block = %d\n\n", blocks[len(blocks)-1].MaxState)

	fmt.Fprintln(&output, "const (")

	for _, block := range blocks {
		fmt.Fprintf(&output, "\t%s Block = %d\n", goName(block.Name), block.DefaultState)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "const (")

	for _, block := range blocks {
		fmt.Fprintf(&output, "\t%sID BlockID = %d\n", goName(block.Name), block.ID)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var blockDefinitions = [...]BlockDefinition{")

	for _, block := range blocks {
		fmt.Fprintf(
			&output,
			"\t{ID: %sID, Name: %q, DefaultState: %s, MinState: %d, MaxState: %d, Behavior: %s, Collision: %s, Emission: %d, LightFilter: %d, Sound: %s, Traits: %s, BlockEntityType: %s, Mining: %s, Waterloggable: %t",
			goName(block.Name),
			block.Name,
			goName(block.Name),
			block.MinState,
			block.MaxState,
			blockBehavior(block),
			blockCollision(block),
			block.EmitLight,
			block.FilterLight,
			blockSoundType(block),
			blockTraits(miningTags, block.Name),
			blockEntityType(block.Name),
			blockMining(block, miningTags, drops[block.Name]),
			hasBlockProperty(block.Properties, "waterlogged"),
		)

		if len(block.Properties) != 0 {
			fmt.Fprint(&output, ", Properties: []BlockProperty{")

			for _, property := range block.Properties {
				values := property.Values

				if property.Type == "bool" {
					values = []string{"true", "false"}
				}

				fmt.Fprintf(&output, "{Name: %q, Values: []string{", property.Name)

				for _, value := range values {
					fmt.Fprintf(&output, "%q,", value)
				}

				fmt.Fprint(&output, "}},")
			}

			fmt.Fprint(&output, "}")
		}

		fmt.Fprintln(&output, "},")
	}

	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var stateFluidStates = [...]fluidStateData{")

	for _, block := range blocks {
		for state := block.MinState; state <= block.MaxState; state++ {
			fluidType, level, occupied := blockFluidState(block, state)
			if !occupied {
				continue
			}

			fmt.Fprintf(&output, "\t%d: {fluidType: %s, level: %d},\n", state, fluidType, level)
		}
	}

	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var stateLightProperties = [...]uint8{")

	for _, block := range blocks {
		for state := block.MinState; state <= block.MaxState; state++ {
			emission := stateEmission(block, state)
			fmt.Fprintf(&output, "%d,", emission|block.FilterLight<<4)

			if state == block.MaxState {
				break
			}
		}
	}

	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var stateBlockIDs = [...]BlockID{")

	for _, block := range blocks {
		for state := block.MinState; state <= block.MaxState; state++ {
			fmt.Fprintf(&output, "%d,", block.ID)

			if state == block.MaxState {
				break
			}
		}
	}

	fmt.Fprintln(&output, "}")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return formatted, nil
}

func readMiningTags(root string) (MiningTags, error) {
	traits := make(map[string][]string)

	traitTags := []MiningTagMapping{
		{Name: "replaceable", Value: "BlockTraitReplaceable"},
		{Name: "dirt", Value: "BlockTraitDirt"},
		{Name: "snow_layer_cannot_survive_on", Value: "BlockTraitSnowCannotSurviveOn"},
		{Name: "snow_layer_can_survive_on", Value: "BlockTraitSnowCanSurviveOn"},
		{Name: "mineable/pickaxe", Value: "BlockTraitMineablePickaxe"},
		{Name: "mineable/shovel", Value: "BlockTraitMineableShovel"},
		{Name: "mineable/axe", Value: "BlockTraitMineableAxe"},
		{Name: "mineable/hoe", Value: "BlockTraitMineableHoe"},
		{Name: "incorrect_for_wooden_tool", Value: "BlockTraitIncorrectWoodenTool"},
		{Name: "incorrect_for_stone_tool", Value: "BlockTraitIncorrectStoneTool"},
		{Name: "incorrect_for_copper_tool", Value: "BlockTraitIncorrectCopperTool"},
		{Name: "incorrect_for_iron_tool", Value: "BlockTraitIncorrectIronTool"},
		{Name: "incorrect_for_diamond_tool", Value: "BlockTraitIncorrectDiamondTool"},
		{Name: "incorrect_for_gold_tool", Value: "BlockTraitIncorrectGoldTool"},
		{Name: "incorrect_for_netherite_tool", Value: "BlockTraitIncorrectNetheriteTool"},
		{Name: "sword_instantly_mines", Value: "BlockTraitSwordInstantlyMines"},
		{Name: "sword_efficient", Value: "BlockTraitSwordEfficient"},
		{Name: "leaves", Value: "BlockTraitLeaves"},
		{Name: "wool", Value: "BlockTraitWool"},
	}

	for _, tag := range traitTags {
		values, err := expandTag(root, tag.Name, make(map[string]bool))
		if err != nil {
			return MiningTags{}, err
		}

		for name := range values {
			traits[name] = append(traits[name], tag.Value)
		}
	}

	return MiningTags{Traits: traits}, nil
}

func blockTraits(tags MiningTags, name string) string {
	values := append([]string(nil), tags.Traits[name]...)

	if fluidExcludedBlock(name) {
		values = append(values, "BlockTraitFluidExcluded")
	}

	if len(values) == 0 {
		return "0"
	}

	return strings.Join(values, " | ")
}

func fluidExcludedBlock(name string) bool {
	if strings.HasSuffix(name, "_door") || strings.HasSuffix(name, "_sign") {
		return true
	}

	switch name {
	case "ladder", "sugar_cane", "bubble_column", "nether_portal", "end_portal", "end_gateway", "structure_void":
		return true
	default:
		return false
	}
}

func expandTag(root, name string, visiting map[string]bool) (map[string]struct{}, error) {
	name = strings.TrimPrefix(name, "minecraft:")
	if visiting[name] {
		return nil, fmt.Errorf("cyclic block tag %s", name)
	}

	visiting[name] = true
	defer delete(visiting, name)

	raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)+".json"))
	if err != nil {
		return nil, fmt.Errorf("read block tag %s: %w", name, err)
	}

	var definition TagDefinition

	err = json.Unmarshal(raw, &definition)
	if err != nil {
		return nil, fmt.Errorf("decode block tag %s: %w", name, err)
	}

	result := make(map[string]struct{})

	for _, rawEntry := range definition.Values {
		var entry string

		err = json.Unmarshal(rawEntry, &entry)
		if err != nil {
			var object TagEntry

			objectErr := json.Unmarshal(rawEntry, &object)
			if objectErr != nil {
				return nil, fmt.Errorf("decode entry in block tag %s: %w", name, err)
			}

			entry = object.ID
		}

		after, ok := strings.CutPrefix(entry, "#")
		if ok {
			nested, err := expandTag(root, after, visiting)
			if err != nil {
				return nil, err
			}

			for nestedName := range nested {
				result[nestedName] = struct{}{}
			}

			continue
		}

		result[strings.TrimPrefix(entry, "minecraft:")] = struct{}{}
	}

	return result, nil
}

func readItemIDs(path string) (map[string]uint16, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read items: %w", err)
	}

	var items []ItemDefinition

	err = json.Unmarshal(raw, &items)
	if err != nil {
		return nil, fmt.Errorf("decode items: %w", err)
	}

	result := make(map[string]uint16, len(items))

	for _, item := range items {
		result[item.Name] = item.ID
	}

	return result, nil
}

func readBlockDrops(root string, blocks []BlockDefinition, itemIDs map[string]uint16) (map[string]BlockDrop, error) {
	result := make(map[string]BlockDrop, len(blocks))

	for _, block := range blocks {
		if !block.Diggable {
			result[block.Name] = noBlockDrop()

			continue
		}

		path := filepath.Join(root, block.Name+".json")

		raw, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				drop := deferredBlockDrop()

				if len(block.Drops) == 0 {
					drop = noBlockDrop()
				}

				result[block.Name] = drop

				continue
			}

			return nil, fmt.Errorf("read loot table for %s: %w", block.Name, err)
		}

		var table LootTable

		err = json.Unmarshal(raw, &table)
		if err != nil {
			return nil, fmt.Errorf("decode loot table for %s: %w", block.Name, err)
		}

		drop, valid := classifyBlockDrop(block.Name, table, itemIDs)
		if !valid {
			drop = deferredBlockDrop()
		}

		result[block.Name] = drop
	}

	return result, nil
}

func classifyBlockDrop(blockName string, table LootTable, itemIDs map[string]uint16) (BlockDrop, bool) {
	if table.Type != "minecraft:block" {
		return BlockDrop{}, false
	}

	if len(table.Pools) == 0 {
		return noBlockDrop(), true
	}

	if len(table.Pools) != 1 {
		return BlockDrop{}, false
	}

	pool := table.Pools[0]
	if pool.Rolls != 1 || pool.BonusRolls != 0 || len(pool.Entries) != 1 || len(pool.Functions) != 0 {
		return BlockDrop{}, false
	}

	property, value, requiresActor, valid := classifyPoolConditions(pool.Conditions, blockName)
	if !valid {
		return BlockDrop{}, false
	}

	entry := pool.Entries[0]
	if entry.Type == "minecraft:alternatives" {
		if len(entry.Children) == 2 && invertedSilkAlternatives(entry.Children[0]) {
			drop, alternativesValid := classifyStateAlternatives(entry.Children[0].Children, blockName, itemIDs)
			if !alternativesValid {
				return BlockDrop{}, false
			}

			drop.RequiresActor = requiresActor

			return drop, true
		}

		if len(entry.Children) != 2 || len(entry.Conditions) != 0 || len(entry.Functions) != 0 || entry.Weight != 0 || entry.Quality != 0 {
			return BlockDrop{}, false
		}

		if !silkTouchEntry(entry.Children[0]) {
			return BlockDrop{}, false
		}

		entry = entry.Children[1]
	}

	drop, valid := classifyLootItem(entry, blockName, itemIDs)
	if !valid {
		return BlockDrop{}, false
	}

	property, value, valid = mergeDropGate(property, value, drop.Property, drop.Value)
	if !valid {
		return BlockDrop{}, false
	}

	drop.Property = property
	drop.Value = value
	drop.RequiresActor = requiresActor

	if property != "" {
		drop.Kind = "BlockDropStateExact"
	}

	return drop, true
}

func classifyPoolConditions(conditions []LootCondition, blockName string) (string, string, bool, bool) {
	filtered := make([]LootCondition, 0, len(conditions))
	requiresActor := false

	for _, condition := range conditions {
		if condition.Condition == "minecraft:entity_properties" && condition.Entity == "this" {
			requiresActor = true

			continue
		}

		filtered = append(filtered, condition)
	}

	property, value, valid := classifyLootConditions(filtered, blockName)
	return property, value, requiresActor, valid
}

func invertedSilkAlternatives(entry LootEntry) bool {
	if entry.Type != "minecraft:alternatives" || len(entry.Children) == 0 || len(entry.Conditions) != 1 {
		return false
	}

	condition := entry.Conditions[0]
	return condition.Condition == "minecraft:inverted" && len(condition.Term) != 0
}

func classifyStateAlternatives(entries []LootEntry, blockName string, itemIDs map[string]uint16) (BlockDrop, bool) {
	if len(entries) == 0 {
		return BlockDrop{}, false
	}

	var result BlockDrop

	for index, entry := range entries {
		drop, valid := classifyLootItem(entry, blockName, itemIDs)
		if !valid || drop.Property == "" || drop.Value == "" || drop.MinCount != drop.MaxCount {
			return BlockDrop{}, false
		}

		if index == 0 {
			result = drop
			result.Property = ""
			result.Value = ""
			result.CountProperty = drop.Property
			result.Counts = nil
		} else if drop.Item != result.Item || drop.Property != result.CountProperty {
			return BlockDrop{}, false
		}

		result.Counts = append(result.Counts, BlockDropCount{Value: drop.Value, Count: drop.MinCount})
	}

	result.MinCount = 1
	result.MaxCount = 1

	return result, true
}

func classifyLootItem(entry LootEntry, blockName string, itemIDs map[string]uint16) (BlockDrop, bool) {
	if entry.Type != "minecraft:item" || entry.Name == "" || len(entry.Children) != 0 || entry.Weight != 0 || entry.Quality != 0 {
		return BlockDrop{}, false
	}

	property, value, valid := classifyLootConditions(entry.Conditions, blockName)
	if !valid {
		return BlockDrop{}, false
	}

	count := int32(1)
	countProperty := ""
	counts := make([]BlockDropCount, 0)
	deferred := false

	for _, function := range entry.Functions {
		switch function.Function {
		case "minecraft:explosion_decay":
			if len(function.Conditions) != 0 {
				return BlockDrop{}, false
			}
		case "minecraft:copy_components", "minecraft:copy_state":
			deferred = true
		case "minecraft:apply_bonus":
			if len(function.Conditions) != 0 {
				return BlockDrop{}, false
			}

			if function.Enchantment != "minecraft:fortune" || function.Formula != "minecraft:ore_drops" {
				return BlockDrop{}, false
			}
		case "minecraft:set_count":
			var value float64

			err := json.Unmarshal(function.Count, &value)
			if err != nil || value < 1 || value != float64(int32(value)) {
				return BlockDrop{}, false
			}

			if len(function.Conditions) == 0 {
				count = int32(value)

				continue
			}

			functionProperty, functionValue, conditionValid := classifyLootConditions(function.Conditions, blockName)
			if !conditionValid || functionProperty == "" || countProperty != "" && countProperty != functionProperty {
				return BlockDrop{}, false
			}

			countProperty = functionProperty
			counts = append(counts, BlockDropCount{Value: functionValue, Count: int32(value)})
		default:
			return BlockDrop{}, false
		}
	}

	itemName := strings.TrimPrefix(entry.Name, "minecraft:")

	itemID, valid := itemIDs[itemName]
	if !valid {
		return BlockDrop{}, false
	}

	kind := "BlockDropExact"

	if deferred {
		kind = "BlockDropDeferred"
	}

	return BlockDrop{
		Kind:          kind,
		Item:          fmt.Sprintf("Item(%d)", itemID),
		MinCount:      count,
		MaxCount:      count,
		Property:      property,
		Value:         value,
		CountProperty: countProperty,
		Counts:        counts,
	}, true
}

func classifyLootConditions(conditions []LootCondition, blockName string) (string, string, bool) {
	var (
		property string
		value    string
	)

	for _, condition := range conditions {
		switch condition.Condition {
		case "minecraft:survives_explosion":
		case "minecraft:block_state_property":
			if strings.TrimPrefix(condition.Block, "minecraft:") != blockName || len(condition.Properties) != 1 {
				return "", "", false
			}

			for candidateProperty, candidateValue := range condition.Properties {
				var valid bool

				property, value, valid = mergeDropGate(property, value, candidateProperty, candidateValue)
				if !valid {
					return "", "", false
				}
			}
		default:
			return "", "", false
		}
	}

	return property, value, true
}

func mergeDropGate(property, value, candidateProperty, candidateValue string) (string, string, bool) {
	if candidateProperty == "" {
		return property, value, true
	}

	if property == "" {
		return candidateProperty, candidateValue, true
	}

	return property, value, property == candidateProperty && value == candidateValue
}

func silkTouchEntry(entry LootEntry) bool {
	if entry.Type != "minecraft:item" || len(entry.Conditions) != 1 || len(entry.Functions) != 0 || len(entry.Children) != 0 || entry.Weight != 0 || entry.Quality != 0 {
		return false
	}

	condition := entry.Conditions[0]
	if condition.Condition != "minecraft:match_tool" || len(condition.Predicate.Predicates) != 1 {
		return false
	}

	raw, valid := condition.Predicate.Predicates["minecraft:enchantments"]
	if !valid {
		return false
	}

	var requirements []LootEnchantmentRequirement

	err := json.Unmarshal(raw, &requirements)
	if err != nil || len(requirements) != 1 {
		return false
	}

	requirement := requirements[0]

	return requirement.Enchantments == "minecraft:silk_touch" && requirement.Levels.Min >= 1
}

func noBlockDrop() BlockDrop {
	return BlockDrop{Kind: "BlockDropNone", Item: "0"}
}

func deferredBlockDrop() BlockDrop {
	return BlockDrop{Kind: "BlockDropDeferred", Item: "0"}
}

func blockMining(block BlockDefinition, tags MiningTags, drop BlockDrop) string {
	dropRules := "nil"

	if (drop.Kind == "BlockDropExact" || drop.Kind == "BlockDropStateExact" || drop.Kind == "BlockDropDeferred") && drop.Item != "0" {
		var rules strings.Builder

		fmt.Fprintf(&rules, "[]BlockDropRule{{Item: %s, Count: %d, CountProperty: %q, GateProperty: %q, GateValue: %q, RequiresActor: %t", drop.Item, drop.MinCount, drop.CountProperty, drop.Property, drop.Value, drop.RequiresActor)

		if len(drop.Counts) != 0 {
			rules.WriteString(", Counts: []BlockDropCount{")

			for _, count := range drop.Counts {
				fmt.Fprintf(&rules, "{Value: %q, Count: %d},", count.Value, count.Count)
			}

			rules.WriteString("}")
		}

		rules.WriteString("}}")
		dropRules = rules.String()
	}

	return fmt.Sprintf("BlockMining{Hardness: %g, DropRules: %s, RequiresTool: %t, Destroyable: %t}", block.Hardness, dropRules, len(block.HarvestTools) != 0, block.Diggable && block.Hardness >= 0)
}

func blockEntityType(name string) string {
	switch name {
	case "chest":
		return "BlockEntityTypeChest"
	case "trapped_chest":
		return "BlockEntityTypeTrappedChest"
	case "barrel":
		return "BlockEntityTypeBarrel"
	case "furnace":
		return "BlockEntityTypeFurnace"
	case "smoker":
		return "BlockEntityTypeSmoker"
	case "blast_furnace":
		return "BlockEntityTypeBlastFurnace"
	case "hopper":
		return "BlockEntityTypeHopper"
	}

	if isCopperChest(name) {
		return "BlockEntityTypeChest"
	}

	return "BlockEntityTypeNone"
}

func blockSoundType(block BlockDefinition) string {
	name := block.Name

	switch {
	case name == "air" || strings.HasSuffix(name, "_air"):
		return "BlockSoundEmpty"
	case name == "grass_block" || isSimplePlant(name) || isFlower(name):
		return "BlockSoundGrass"
	case name == "glass" || name == "glass_pane" || strings.HasSuffix(name, "_stained_glass") || strings.HasSuffix(name, "_stained_glass_pane"):
		return "BlockSoundGlass"
	case name == "snow" || name == "snow_block":
		return "BlockSoundSnow"
	case name == "gold_block":
		return "BlockSoundMetal"
	case isCopperChest(name):
		return "BlockSoundCopper"
	case name == "candle" || strings.HasSuffix(name, "_candle"):
		return "BlockSoundCandle"
	case isSimpleCarpet(name):
		return "BlockSoundWool"
	case isWoodenBlock(name):
		return "BlockSoundWood"
	default:
		return "BlockSoundStone"
	}
}

func isFlower(name string) bool {
	switch name {
	case "dandelion", "poppy", "blue_orchid", "allium", "azure_bluet", "red_tulip", "orange_tulip", "white_tulip", "pink_tulip", "oxeye_daisy", "cornflower", "wither_rose", "lily_of_the_valley", "open_eyeblossom", "closed_eyeblossom":
		return true
	default:
		return false
	}
}

func isWoodenBlock(name string) bool {
	woodParts := [...]string{"planks", "log", "wood", "stem", "hyphae", "door", "trapdoor", "fence", "fence_gate", "button", "pressure_plate"}

	for _, part := range woodParts {
		if strings.Contains(name, part) && !strings.HasPrefix(name, "iron_") && !strings.HasPrefix(name, "stone_") && !strings.HasPrefix(name, "polished_blackstone_") {
			return true
		}
	}

	return false
}

func stateEmission(block BlockDefinition, state uint16) uint8 {
	if block.Name == "light" {
		return uint8(propertyInt(block, state, "level"))
	}

	if block.Name == "sea_pickle" {
		if propertyValue(block, state, "waterlogged") != "true" {
			return 0
		}

		return uint8(propertyInt(block, state, "pickles")*3 + 3)
	}

	if block.Name == "respawn_anchor" {
		charges := propertyInt(block, state, "charges")
		if charges == 0 {
			return 0
		}

		return uint8(charges*4 - 1)
	}

	if block.Name == "cave_vines" || block.Name == "cave_vines_plant" {
		if propertyValue(block, state, "berries") != "true" {
			return 0
		}
	}

	if block.Name == "sculk_sensor" || block.Name == "calibrated_sculk_sensor" {
		if propertyValue(block, state, "sculk_sensor_phase") != "active" {
			return 0
		}
	}

	if propertyValue(block, state, "lit") == "false" {
		return 0
	}

	switch block.Name {
	case "furnace", "smoker", "blast_furnace":
		return 13
	case "redstone_ore", "deepslate_redstone_ore":
		return 9
	case "redstone_lamp":
		return 15
	}

	if block.Name == "candle" || strings.HasSuffix(block.Name, "_candle") {
		return uint8(propertyInt(block, state, "candles") * 3)
	}

	if strings.HasSuffix(block.Name, "candle_cake") {
		return 3
	}

	copperBulb := strings.TrimPrefix(block.Name, "waxed_")

	switch copperBulb {
	case "copper_bulb":
		return 15
	case "exposed_copper_bulb":
		return 12
	case "weathered_copper_bulb":
		return 8
	case "oxidized_copper_bulb":
		return 4
	}

	return block.EmitLight
}

func propertyInt(block BlockDefinition, state uint16, name string) int {
	value := propertyValue(block, state, name)
	if value == "" {
		return 0
	}

	var result int
	_, _ = fmt.Sscanf(value, "%d", &result)

	return result
}

func propertyValue(block BlockDefinition, state uint16, name string) string {
	offset := int(state - block.MinState)

	for _, property := range slices.Backward(block.Properties) {
		values := property.Values

		if property.Type == "bool" {
			values = []string{"true", "false"}
		}

		valueIndex := offset % len(values)
		offset /= len(values)

		if property.Name == name {
			return values[valueIndex]
		}
	}

	return ""
}

func hasBlockProperty(properties []BlockProperty, name string) bool {
	for _, property := range properties {
		if property.Name == name {
			return true
		}
	}

	return false
}

func blockFluidState(block BlockDefinition, state uint16) (fluidType string, level int, occupied bool) {
	switch block.Name {
	case "water":
		return "FluidTypeWater", propertyInt(block, state, "level"), true
	case "lava":
		return "FluidTypeLava", propertyInt(block, state, "level"), true
	default:
		if propertyValue(block, state, "waterlogged") == "true" {
			return "FluidTypeWater", 0, true
		}

		return "", 0, false
	}
}

func blockBehavior(block BlockDefinition) string {
	if strings.HasSuffix(block.Name, "_chain") {
		return "BlockBehaviorNone"
	}

	if block.Name == "pale_moss_carpet" {
		return "BlockBehaviorNone"
	}

	switch {
	case block.Name == "chest" || block.Name == "trapped_chest" || isCopperChest(block.Name):
		return "BlockBehaviorChest"
	case strings.HasSuffix(block.Name, "_slab"):
		return "BlockBehaviorSlab"
	case strings.HasSuffix(block.Name, "_stairs"):
		return "BlockBehaviorStairs"
	case strings.HasSuffix(block.Name, "_trapdoor"):
		return "BlockBehaviorTrapdoor"
	case strings.HasSuffix(block.Name, "_door"):
		return "BlockBehaviorDoor"
	case strings.HasSuffix(block.Name, "_fence_gate"):
		return "BlockBehaviorFenceGate"
	case strings.HasSuffix(block.Name, "_fence"):
		return "BlockBehaviorFence"
	case block.Name == "iron_bars" || strings.HasSuffix(block.Name, "copper_bars") || strings.HasSuffix(block.Name, "_glass_pane") || block.Name == "glass_pane":
		return "BlockBehaviorPane"
	case strings.HasSuffix(block.Name, "_wall"):
		return "BlockBehaviorWall"
	case isSimpleCarpet(block.Name) || block.Name == "snow" || block.Name == "candle" || strings.HasSuffix(block.Name, "_candle") || block.Name == "cake" || strings.HasSuffix(block.Name, "_candle_cake") || strings.HasSuffix(block.Name, "_pressure_plate"):
		return "BlockBehaviorSupported"
	case strings.HasSuffix(block.Name, "_button"):
		return "BlockBehaviorButton"
	case isSimplePlant(block.Name):
		return "BlockBehaviorPlant"
	case block.Name == "pointed_dripstone":
		return "BlockBehaviorPointedDripstone"
	case horizontalFacingProperties(block.Properties):
		return "BlockBehaviorHorizontalFacing"
	case block.BoundingBox == "block":
		return "BlockBehaviorSolid"
	default:
		return "BlockBehaviorNone"
	}
}

func blockCollision(block BlockDefinition) string {
	if strings.HasSuffix(block.Name, "_chain") {
		return "BlockCollisionChain"
	}

	switch {
	case block.Name == "chest" || block.Name == "trapped_chest" || isCopperChest(block.Name):
		return "BlockCollisionChest"
	case block.Name == "hopper":
		return "BlockCollisionHopper"
	case strings.HasSuffix(block.Name, "_slab"):
		return "BlockCollisionSlab"
	case strings.HasSuffix(block.Name, "_stairs"):
		return "BlockCollisionStairs"
	case strings.HasSuffix(block.Name, "_trapdoor"):
		return "BlockCollisionTrapdoor"
	case strings.HasSuffix(block.Name, "_door"):
		return "BlockCollisionDoor"
	case strings.HasSuffix(block.Name, "_fence_gate"):
		return "BlockCollisionFenceGate"
	case strings.HasSuffix(block.Name, "_fence"):
		return "BlockCollisionFence"
	case block.Name == "iron_bars" || strings.HasSuffix(block.Name, "copper_bars") || strings.HasSuffix(block.Name, "_glass_pane") || block.Name == "glass_pane":
		return "BlockCollisionPane"
	case strings.HasSuffix(block.Name, "_wall"):
		return "BlockCollisionWall"
	case strings.HasSuffix(block.Name, "_carpet") || block.Name == "moss_carpet":
		return "BlockCollisionCarpet"
	case block.Name == "snow":
		return "BlockCollisionSnow"
	case block.Name == "candle" || strings.HasSuffix(block.Name, "_candle"):
		return "BlockCollisionNone"
	case block.Name == "pointed_dripstone":
		return "BlockCollisionPointedDripstone"
	case block.Name == "cake" || strings.HasSuffix(block.Name, "_candle_cake"):
		return "BlockCollisionCake"
	case block.BoundingBox == "block":
		return "BlockCollisionFull"
	default:
		return "BlockCollisionNone"
	}
}

func isCopperChest(name string) bool {
	return name == "copper_chest" || strings.HasSuffix(name, "_copper_chest")
}

func isSimplePlant(name string) bool {
	switch name {
	case "short_grass", "fern", "dead_bush", "bush", "short_dry_grass", "tall_dry_grass",
		"dandelion", "poppy", "blue_orchid", "allium", "azure_bluet", "red_tulip",
		"orange_tulip", "white_tulip", "pink_tulip", "oxeye_daisy", "cornflower",
		"wither_rose", "lily_of_the_valley", "open_eyeblossom", "closed_eyeblossom",
		"firefly_bush":
		return true
	default:
		return false
	}
}

func isSimpleCarpet(name string) bool {
	return name != "pale_moss_carpet" && (name == "moss_carpet" || strings.HasSuffix(name, "_carpet"))
}

func horizontalFacingProperties(properties []BlockProperty) bool {
	if len(properties) != 1 || properties[0].Name != "facing" {
		return false
	}

	values := properties[0].Values
	return len(values) == 4 && values[0] == "north" && values[1] == "south" && values[2] == "west" && values[3] == "east"
}

func goName(name string) string {
	parts := strings.Split(name, "_")

	for index, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}

		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}

	return strings.Join(parts, "")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)

	os.Exit(1)
}
