package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strings"
	"unicode"
)

type BlockProperty struct {
	Name      string   `json:"name"`
	Type      string   `json:"type"`
	NumValues int      `json:"num_values"`
	Values    []string `json:"values"`
}

type BlockDefinition struct {
	ID           uint16          `json:"id"`
	Name         string          `json:"name"`
	DefaultState uint16          `json:"defaultState"`
	MinState     uint16          `json:"minStateId"`
	MaxState     uint16          `json:"maxStateId"`
	Properties   []BlockProperty `json:"states"`
	BoundingBox  string          `json:"boundingBox"`
	EmitLight    uint8           `json:"emitLight"`
	FilterLight  uint8           `json:"filterLight"`
}

func main() {
	input := flag.String("input", "", "path to blocks.json")
	output := flag.String("output", "", "generated Go output path")

	flag.Parse()

	if *input == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "input and output are required")

		os.Exit(2)
	}

	raw, err := os.ReadFile(*input)
	if err != nil {
		fail(err)
	}

	var blocks []BlockDefinition

	err = json.Unmarshal(raw, &blocks)
	if err != nil {
		fail(err)
	}

	generated, err := generate(blocks)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*output, generated, 0o644)
	if err != nil {
		fail(err)
	}
}

func generate(blocks []BlockDefinition) ([]byte, error) {
	if len(blocks) == 0 {
		return nil, fmt.Errorf("block catalogue is empty")
	}

	for index, block := range blocks {
		if int(block.ID) != index {
			return nil, fmt.Errorf("block ID %d at index %d is not contiguous", block.ID, index)
		}

		if index > 0 && block.MinState != blocks[index-1].MaxState+1 {
			return nil, fmt.Errorf("state range for %s is not contiguous", block.Name)
		}
	}

	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-blocks; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package game")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "const MaxBlockID BlockID = %d\n", blocks[len(blocks)-1].ID)
	fmt.Fprintf(&output, "const MaxBlockState Block = %d\n\n", blocks[len(blocks)-1].MaxState)

	fmt.Fprintln(&output, "const (")

	for _, block := range blocks {
		fmt.Fprintf(&output, "\t%s Block = %d\n", goName(block.Name), block.DefaultState)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "const (")

	for _, block := range blocks {
		fmt.Fprintf(&output, "\t%sID BlockID = %d\n", goName(block.Name), block.ID)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var blockDefinitions = [...]BlockDefinition{")

	for _, block := range blocks {
		fmt.Fprintf(
			&output,
			"\t{ID: %sID, Name: %q, DefaultState: %s, MinState: %d, MaxState: %d, Behavior: %s, Emission: %d, LightFilter: %d",
			goName(block.Name),
			block.Name,
			goName(block.Name),
			block.MinState,
			block.MaxState,
			blockBehavior(block),
			block.EmitLight,
			block.FilterLight,
		)

		if len(block.Properties) != 0 {
			fmt.Fprint(&output, ", Properties: []BlockProperty{")

			for _, property := range block.Properties {
				values := property.Values
				if property.Type == "bool" {
					values = []string{"true", "false"}
				}

				fmt.Fprintf(&output, "{Name: %q, Values: []string{", property.Name)

				for _, value := range values {
					fmt.Fprintf(&output, "%q,", value)
				}

				fmt.Fprint(&output, "}},")
			}

			fmt.Fprint(&output, "}")
		}

		fmt.Fprintln(&output, "},")
	}

	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var stateLightProperties = [...]uint8{")

	for _, block := range blocks {
		for state := block.MinState; state <= block.MaxState; state++ {
			emission := stateEmission(block, state)
			fmt.Fprintf(&output, "%d,", emission|block.FilterLight<<4)

			if state == block.MaxState {
				break
			}
		}
	}

	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var stateBlockIDs = [...]BlockID{")

	for _, block := range blocks {
		for state := block.MinState; state <= block.MaxState; state++ {
			fmt.Fprintf(&output, "%d,", block.ID)

			if state == block.MaxState {
				break
			}
		}
	}

	fmt.Fprintln(&output, "}")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return formatted, nil
}

func stateEmission(block BlockDefinition, state uint16) uint8 {
	if block.Name == "light" {
		return uint8(propertyInt(block, state, "level"))
	}

	if block.Name == "sea_pickle" {
		if propertyValue(block, state, "waterlogged") != "true" {
			return 0
		}

		return uint8(propertyInt(block, state, "pickles")*3 + 3)
	}

	if block.Name == "respawn_anchor" {
		charges := propertyInt(block, state, "charges")
		if charges == 0 {
			return 0
		}

		return uint8(charges*4 - 1)
	}

	if block.Name == "cave_vines" || block.Name == "cave_vines_plant" {
		if propertyValue(block, state, "berries") != "true" {
			return 0
		}
	}

	if block.Name == "sculk_sensor" || block.Name == "calibrated_sculk_sensor" {
		if propertyValue(block, state, "sculk_sensor_phase") != "active" {
			return 0
		}
	}

	if propertyValue(block, state, "lit") == "false" {
		return 0
	}

	switch block.Name {
	case "furnace", "smoker", "blast_furnace":
		return 13
	case "redstone_ore", "deepslate_redstone_ore":
		return 9
	case "redstone_lamp":
		return 15
	}

	if block.Name == "candle" || strings.HasSuffix(block.Name, "_candle") {
		return uint8(propertyInt(block, state, "candles") * 3)
	}

	if strings.HasSuffix(block.Name, "candle_cake") {
		return 3
	}

	copperBulb := strings.TrimPrefix(block.Name, "waxed_")

	switch copperBulb {
	case "copper_bulb":
		return 15
	case "exposed_copper_bulb":
		return 12
	case "weathered_copper_bulb":
		return 8
	case "oxidized_copper_bulb":
		return 4
	}

	return block.EmitLight
}

func propertyInt(block BlockDefinition, state uint16, name string) int {
	value := propertyValue(block, state, name)
	if value == "" {
		return 0
	}

	var result int
	_, _ = fmt.Sscanf(value, "%d", &result)

	return result
}

func propertyValue(block BlockDefinition, state uint16, name string) string {
	offset := int(state - block.MinState)

	for _, property := range slices.Backward(block.Properties) {
		values := property.Values

		if property.Type == "bool" {
			values = []string{"true", "false"}
		}

		valueIndex := offset % len(values)
		offset /= len(values)

		if property.Name == name {
			return values[valueIndex]
		}
	}

	return ""
}

func blockBehavior(block BlockDefinition) string {
	switch {
	case block.Name == "iron_door" || block.Name == "iron_trapdoor":
		return "BlockBehaviorNone"
	case strings.HasSuffix(block.Name, "_slab"):
		return "BlockBehaviorSlab"
	case strings.HasSuffix(block.Name, "_stairs"):
		return "BlockBehaviorStairs"
	case strings.HasSuffix(block.Name, "_trapdoor"):
		return "BlockBehaviorTrapdoor"
	case strings.HasSuffix(block.Name, "_door"):
		return "BlockBehaviorDoor"
	case strings.HasSuffix(block.Name, "_fence_gate"):
		return "BlockBehaviorFenceGate"
	case strings.HasSuffix(block.Name, "_fence"):
		return "BlockBehaviorFence"
	case block.Name == "iron_bars" || strings.HasSuffix(block.Name, "_glass_pane") || block.Name == "glass_pane":
		return "BlockBehaviorPane"
	case strings.HasSuffix(block.Name, "_wall"):
		return "BlockBehaviorWall"
	case horizontalFacingProperties(block.Properties):
		return "BlockBehaviorHorizontalFacing"
	case block.BoundingBox == "block":
		return "BlockBehaviorSolid"
	default:
		return "BlockBehaviorNone"
	}
}

func horizontalFacingProperties(properties []BlockProperty) bool {
	if len(properties) != 1 || properties[0].Name != "facing" {
		return false
	}

	values := properties[0].Values
	return len(values) == 4 && values[0] == "north" && values[1] == "south" && values[2] == "west" && values[3] == "east"
}

func goName(name string) string {
	parts := strings.Split(name, "_")

	for index, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}

		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}

	return strings.Join(parts, "")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)

	os.Exit(1)
}
