package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"
)

type BlockProperty struct {
	Name      string   `json:"name"`
	Type      string   `json:"type"`
	NumValues int      `json:"num_values"`
	Values    []string `json:"values"`
}

type BlockDefinition struct {
	ID           uint16          `json:"id"`
	Name         string          `json:"name"`
	DefaultState uint16          `json:"defaultState"`
	MinState     uint16          `json:"minStateId"`
	MaxState     uint16          `json:"maxStateId"`
	Properties   []BlockProperty `json:"states"`
	BoundingBox  string          `json:"boundingBox"`
	EmitLight    uint8           `json:"emitLight"`
	FilterLight  uint8           `json:"filterLight"`
	Hardness     float32         `json:"hardness"`
	Diggable     bool            `json:"diggable"`
	HarvestTools map[string]bool `json:"harvestTools"`
	Drops        []uint16        `json:"drops"`
}

type TagDefinition struct {
	Values []json.RawMessage `json:"values"`
}

type TagEntry struct {
	ID string `json:"id"`
}

type MiningTags struct {
	Tools map[string]string
	Tiers map[string]string
}

type MiningTagMapping struct {
	Name  string
	Value string
}

func main() {
	input := flag.String("input", "", "path to blocks.json")
	tagsPath := flag.String("tags", "", "path to canonical block tags")
	output := flag.String("output", "", "generated Go output path")

	flag.Parse()

	if *input == "" || *tagsPath == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "input, tags and output are required")

		os.Exit(2)
	}

	raw, err := os.ReadFile(*input)
	if err != nil {
		fail(err)
	}

	var blocks []BlockDefinition

	err = json.Unmarshal(raw, &blocks)
	if err != nil {
		fail(err)
	}

	miningTags, err := readMiningTags(*tagsPath)
	if err != nil {
		fail(err)
	}

	generated, err := generate(blocks, miningTags)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*output, generated, 0o644)
	if err != nil {
		fail(err)
	}
}

func generate(blocks []BlockDefinition, miningTags MiningTags) ([]byte, error) {
	if len(blocks) == 0 {
		return nil, fmt.Errorf("block catalogue is empty")
	}

	for index, block := range blocks {
		if int(block.ID) != index {
			return nil, fmt.Errorf("block ID %d at index %d is not contiguous", block.ID, index)
		}

		if index > 0 && block.MinState != blocks[index-1].MaxState+1 {
			return nil, fmt.Errorf("state range for %s is not contiguous", block.Name)
		}
	}

	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-blocks; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package game")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "const MaxBlockID BlockID = %d\n", blocks[len(blocks)-1].ID)
	fmt.Fprintf(&output, "const MaxBlockState Block = %d\n\n", blocks[len(blocks)-1].MaxState)

	fmt.Fprintln(&output, "const (")

	for _, block := range blocks {
		fmt.Fprintf(&output, "\t%s Block = %d\n", goName(block.Name), block.DefaultState)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "const (")

	for _, block := range blocks {
		fmt.Fprintf(&output, "\t%sID BlockID = %d\n", goName(block.Name), block.ID)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var blockDefinitions = [...]BlockDefinition{")

	for _, block := range blocks {
		fmt.Fprintf(
			&output,
			"\t{ID: %sID, Name: %q, DefaultState: %s, MinState: %d, MaxState: %d, Behavior: %s, Collision: %s, Emission: %d, LightFilter: %d, Sound: %s, Replaceable: %t, BlockEntityType: %s, Mining: %s",
			goName(block.Name),
			block.Name,
			goName(block.Name),
			block.MinState,
			block.MaxState,
			blockBehavior(block),
			blockCollision(block),
			block.EmitLight,
			block.FilterLight,
			blockSoundType(block),
			blockReplaceable(block.Name),
			blockEntityType(block.Name),
			blockMining(block, miningTags),
		)

		if len(block.Properties) != 0 {
			fmt.Fprint(&output, ", Properties: []BlockProperty{")

			for _, property := range block.Properties {
				values := property.Values
				if property.Type == "bool" {
					values = []string{"true", "false"}
				}

				fmt.Fprintf(&output, "{Name: %q, Values: []string{", property.Name)

				for _, value := range values {
					fmt.Fprintf(&output, "%q,", value)
				}

				fmt.Fprint(&output, "}},")
			}

			fmt.Fprint(&output, "}")
		}

		fmt.Fprintln(&output, "},")
	}

	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var stateLightProperties = [...]uint8{")

	for _, block := range blocks {
		for state := block.MinState; state <= block.MaxState; state++ {
			emission := stateEmission(block, state)
			fmt.Fprintf(&output, "%d,", emission|block.FilterLight<<4)

			if state == block.MaxState {
				break
			}
		}
	}

	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "var stateBlockIDs = [...]BlockID{")

	for _, block := range blocks {
		for state := block.MinState; state <= block.MaxState; state++ {
			fmt.Fprintf(&output, "%d,", block.ID)

			if state == block.MaxState {
				break
			}
		}
	}

	fmt.Fprintln(&output, "}")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return formatted, nil
}

func readMiningTags(root string) (MiningTags, error) {
	tools := make(map[string]string)
	tiers := make(map[string]string)

	toolTags := []MiningTagMapping{
		{Name: "mineable/pickaxe", Value: "ToolPickaxe"},
		{Name: "mineable/shovel", Value: "ToolShovel"},
		{Name: "mineable/axe", Value: "ToolAxe"},
		{Name: "mineable/hoe", Value: "ToolHoe"},
	}

	for _, tag := range toolTags {
		values, err := expandTag(root, tag.Name, make(map[string]bool))
		if err != nil {
			return MiningTags{}, err
		}

		for name := range values {
			tools[name] = tag.Value
		}
	}

	tierTags := []MiningTagMapping{
		{Name: "needs_stone_tool", Value: "HarvestTierStone"},
		{Name: "needs_iron_tool", Value: "HarvestTierIron"},
		{Name: "needs_diamond_tool", Value: "HarvestTierDiamond"},
	}

	for _, tag := range tierTags {
		values, err := expandTag(root, tag.Name, make(map[string]bool))
		if err != nil {
			return MiningTags{}, err
		}

		for name := range values {
			tiers[name] = tag.Value
		}
	}

	return MiningTags{Tools: tools, Tiers: tiers}, nil
}

func expandTag(root, name string, visiting map[string]bool) (map[string]struct{}, error) {
	name = strings.TrimPrefix(name, "minecraft:")
	if visiting[name] {
		return nil, fmt.Errorf("cyclic block tag %s", name)
	}

	visiting[name] = true
	defer delete(visiting, name)

	raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)+".json"))
	if err != nil {
		return nil, fmt.Errorf("read block tag %s: %w", name, err)
	}

	var definition TagDefinition

	err = json.Unmarshal(raw, &definition)
	if err != nil {
		return nil, fmt.Errorf("decode block tag %s: %w", name, err)
	}

	result := make(map[string]struct{})

	for _, rawEntry := range definition.Values {
		var entry string

		err = json.Unmarshal(rawEntry, &entry)
		if err != nil {
			var object TagEntry
			if objectErr := json.Unmarshal(rawEntry, &object); objectErr != nil {
				return nil, fmt.Errorf("decode entry in block tag %s: %w", name, err)
			}

			entry = object.ID
		}

		if after, ok := strings.CutPrefix(entry, "#"); ok {
			nested, err := expandTag(root, after, visiting)
			if err != nil {
				return nil, err
			}

			for nestedName := range nested {
				result[nestedName] = struct{}{}
			}

			continue
		}

		result[strings.TrimPrefix(entry, "minecraft:")] = struct{}{}
	}

	return result, nil
}

func blockMining(block BlockDefinition, tags MiningTags) string {
	tool := tags.Tools[block.Name]
	if tool == "" {
		tool = "ToolNone"
	}

	tier := tags.Tiers[block.Name]
	if tier == "" {
		tier = "HarvestTierNone"
	}

	dropKind, dropItem, dropMin, dropMax := blockDrop(block)
	return fmt.Sprintf("BlockMining{Hardness: %g, EffectiveTool: %s, RequiredTier: %s, DropKind: %s, DropItem: %s, DropMin: %d, DropMax: %d, RequiresTool: %t, Destroyable: %t}", block.Hardness, tool, tier, dropKind, dropItem, dropMin, dropMax, len(block.HarvestTools) != 0, block.Diggable && block.Hardness >= 0)
}

func blockDrop(block BlockDefinition) (kind, item string, minCount, maxCount int32) {
	if !block.Diggable || len(block.Drops) == 0 {
		return "BlockDropNone", "0", 0, 0
	}

	if !exactBaselineDrop(block.Name) || len(block.Drops) != 1 {
		return "BlockDropDeferred", "0", 0, 0
	}

	return "BlockDropExact", fmt.Sprintf("Item(%d)", block.Drops[0]), 1, 1
}

func exactBaselineDrop(name string) bool {
	switch name {
	case "stone", "dirt", "sand", "oak_log", "chest", "trapped_chest", "barrel", "furnace", "smoker", "blast_furnace",
		"coal_ore", "deepslate_coal_ore", "iron_ore", "deepslate_iron_ore", "gold_ore", "deepslate_gold_ore",
		"diamond_ore", "deepslate_diamond_ore", "emerald_ore", "deepslate_emerald_ore", "nether_quartz_ore",
		"obsidian", "ancient_debris":
		return true
	default:
		return false
	}
}

func blockEntityType(name string) string {
	switch name {
	case "chest":
		return "BlockEntityTypeChest"
	case "trapped_chest":
		return "BlockEntityTypeTrappedChest"
	case "barrel":
		return "BlockEntityTypeBarrel"
	case "furnace":
		return "BlockEntityTypeFurnace"
	case "smoker":
		return "BlockEntityTypeSmoker"
	case "blast_furnace":
		return "BlockEntityTypeBlastFurnace"
	}

	if isCopperChest(name) {
		return "BlockEntityTypeChest"
	}

	return "BlockEntityTypeNone"
}

func blockSoundType(block BlockDefinition) string {
	name := block.Name

	switch {
	case name == "air" || strings.HasSuffix(name, "_air"):
		return "BlockSoundEmpty"
	case name == "grass_block" || isSimplePlant(name) || isFlower(name):
		return "BlockSoundGrass"
	case name == "glass" || name == "glass_pane" || strings.HasSuffix(name, "_stained_glass") || strings.HasSuffix(name, "_stained_glass_pane"):
		return "BlockSoundGlass"
	case name == "snow" || name == "snow_block":
		return "BlockSoundSnow"
	case name == "gold_block":
		return "BlockSoundMetal"
	case isCopperChest(name):
		return "BlockSoundCopper"
	case name == "candle" || strings.HasSuffix(name, "_candle"):
		return "BlockSoundCandle"
	case isSimpleCarpet(name):
		return "BlockSoundWool"
	case isWoodenBlock(name):
		return "BlockSoundWood"
	default:
		return "BlockSoundStone"
	}
}

func blockReplaceable(name string) bool {
	switch name {
	case "short_grass", "fern", "dead_bush", "bush", "short_dry_grass", "tall_dry_grass", "snow":
		return true
	default:
		return false
	}
}

func isFlower(name string) bool {
	switch name {
	case "dandelion", "poppy", "blue_orchid", "allium", "azure_bluet", "red_tulip", "orange_tulip", "white_tulip", "pink_tulip", "oxeye_daisy", "cornflower", "wither_rose", "lily_of_the_valley", "open_eyeblossom", "closed_eyeblossom":
		return true
	default:
		return false
	}
}

func isWoodenBlock(name string) bool {
	woodParts := [...]string{"planks", "log", "wood", "stem", "hyphae", "door", "trapdoor", "fence", "fence_gate", "button", "pressure_plate"}

	for _, part := range woodParts {
		if strings.Contains(name, part) && !strings.HasPrefix(name, "iron_") && !strings.HasPrefix(name, "stone_") && !strings.HasPrefix(name, "polished_blackstone_") {
			return true
		}
	}

	return false
}

func stateEmission(block BlockDefinition, state uint16) uint8 {
	if block.Name == "light" {
		return uint8(propertyInt(block, state, "level"))
	}

	if block.Name == "sea_pickle" {
		if propertyValue(block, state, "waterlogged") != "true" {
			return 0
		}

		return uint8(propertyInt(block, state, "pickles")*3 + 3)
	}

	if block.Name == "respawn_anchor" {
		charges := propertyInt(block, state, "charges")
		if charges == 0 {
			return 0
		}

		return uint8(charges*4 - 1)
	}

	if block.Name == "cave_vines" || block.Name == "cave_vines_plant" {
		if propertyValue(block, state, "berries") != "true" {
			return 0
		}
	}

	if block.Name == "sculk_sensor" || block.Name == "calibrated_sculk_sensor" {
		if propertyValue(block, state, "sculk_sensor_phase") != "active" {
			return 0
		}
	}

	if propertyValue(block, state, "lit") == "false" {
		return 0
	}

	switch block.Name {
	case "furnace", "smoker", "blast_furnace":
		return 13
	case "redstone_ore", "deepslate_redstone_ore":
		return 9
	case "redstone_lamp":
		return 15
	}

	if block.Name == "candle" || strings.HasSuffix(block.Name, "_candle") {
		return uint8(propertyInt(block, state, "candles") * 3)
	}

	if strings.HasSuffix(block.Name, "candle_cake") {
		return 3
	}

	copperBulb := strings.TrimPrefix(block.Name, "waxed_")

	switch copperBulb {
	case "copper_bulb":
		return 15
	case "exposed_copper_bulb":
		return 12
	case "weathered_copper_bulb":
		return 8
	case "oxidized_copper_bulb":
		return 4
	}

	return block.EmitLight
}

func propertyInt(block BlockDefinition, state uint16, name string) int {
	value := propertyValue(block, state, name)
	if value == "" {
		return 0
	}

	var result int
	_, _ = fmt.Sscanf(value, "%d", &result)

	return result
}

func propertyValue(block BlockDefinition, state uint16, name string) string {
	offset := int(state - block.MinState)

	for _, property := range slices.Backward(block.Properties) {
		values := property.Values

		if property.Type == "bool" {
			values = []string{"true", "false"}
		}

		valueIndex := offset % len(values)
		offset /= len(values)

		if property.Name == name {
			return values[valueIndex]
		}
	}

	return ""
}

func blockBehavior(block BlockDefinition) string {
	if strings.HasSuffix(block.Name, "_chain") {
		return "BlockBehaviorNone"
	}

	if block.Name == "pale_moss_carpet" {
		return "BlockBehaviorNone"
	}

	switch {
	case block.Name == "chest" || block.Name == "trapped_chest" || isCopperChest(block.Name):
		return "BlockBehaviorChest"
	case strings.HasSuffix(block.Name, "_slab"):
		return "BlockBehaviorSlab"
	case strings.HasSuffix(block.Name, "_stairs"):
		return "BlockBehaviorStairs"
	case strings.HasSuffix(block.Name, "_trapdoor"):
		return "BlockBehaviorTrapdoor"
	case strings.HasSuffix(block.Name, "_door"):
		return "BlockBehaviorDoor"
	case strings.HasSuffix(block.Name, "_fence_gate"):
		return "BlockBehaviorFenceGate"
	case strings.HasSuffix(block.Name, "_fence"):
		return "BlockBehaviorFence"
	case block.Name == "iron_bars" || strings.HasSuffix(block.Name, "copper_bars") || strings.HasSuffix(block.Name, "_glass_pane") || block.Name == "glass_pane":
		return "BlockBehaviorPane"
	case strings.HasSuffix(block.Name, "_wall"):
		return "BlockBehaviorWall"
	case isSimpleCarpet(block.Name) || block.Name == "snow" || block.Name == "candle" || strings.HasSuffix(block.Name, "_candle") || block.Name == "cake" || strings.HasSuffix(block.Name, "_candle_cake") || strings.HasSuffix(block.Name, "_pressure_plate"):
		return "BlockBehaviorSupported"
	case strings.HasSuffix(block.Name, "_button"):
		return "BlockBehaviorButton"
	case isSimplePlant(block.Name):
		return "BlockBehaviorPlant"
	case block.Name == "pointed_dripstone":
		return "BlockBehaviorPointedDripstone"
	case horizontalFacingProperties(block.Properties):
		return "BlockBehaviorHorizontalFacing"
	case block.BoundingBox == "block":
		return "BlockBehaviorSolid"
	default:
		return "BlockBehaviorNone"
	}
}

func blockCollision(block BlockDefinition) string {
	if strings.HasSuffix(block.Name, "_chain") {
		return "BlockCollisionChain"
	}

	switch {
	case block.Name == "chest" || block.Name == "trapped_chest" || isCopperChest(block.Name):
		return "BlockCollisionChest"
	case strings.HasSuffix(block.Name, "_slab"):
		return "BlockCollisionSlab"
	case strings.HasSuffix(block.Name, "_stairs"):
		return "BlockCollisionStairs"
	case strings.HasSuffix(block.Name, "_trapdoor"):
		return "BlockCollisionTrapdoor"
	case strings.HasSuffix(block.Name, "_door"):
		return "BlockCollisionDoor"
	case strings.HasSuffix(block.Name, "_fence_gate"):
		return "BlockCollisionFenceGate"
	case strings.HasSuffix(block.Name, "_fence"):
		return "BlockCollisionFence"
	case block.Name == "iron_bars" || strings.HasSuffix(block.Name, "copper_bars") || strings.HasSuffix(block.Name, "_glass_pane") || block.Name == "glass_pane":
		return "BlockCollisionPane"
	case strings.HasSuffix(block.Name, "_wall"):
		return "BlockCollisionWall"
	case strings.HasSuffix(block.Name, "_carpet") || block.Name == "moss_carpet":
		return "BlockCollisionCarpet"
	case block.Name == "snow":
		return "BlockCollisionSnow"
	case block.Name == "candle" || strings.HasSuffix(block.Name, "_candle"):
		return "BlockCollisionNone"
	case block.Name == "pointed_dripstone":
		return "BlockCollisionPointedDripstone"
	case block.Name == "cake" || strings.HasSuffix(block.Name, "_candle_cake"):
		return "BlockCollisionCake"
	case block.BoundingBox == "block":
		return "BlockCollisionFull"
	default:
		return "BlockCollisionNone"
	}
}

func isCopperChest(name string) bool {
	return name == "copper_chest" || strings.HasSuffix(name, "_copper_chest")
}

func isSimplePlant(name string) bool {
	switch name {
	case "short_grass", "fern", "dead_bush", "bush", "short_dry_grass", "tall_dry_grass",
		"dandelion", "poppy", "blue_orchid", "allium", "azure_bluet", "red_tulip",
		"orange_tulip", "white_tulip", "pink_tulip", "oxeye_daisy", "cornflower",
		"wither_rose", "lily_of_the_valley", "open_eyeblossom", "closed_eyeblossom",
		"firefly_bush":
		return true
	default:
		return false
	}
}

func isSimpleCarpet(name string) bool {
	return name != "pale_moss_carpet" && (name == "moss_carpet" || strings.HasSuffix(name, "_carpet"))
}

func horizontalFacingProperties(properties []BlockProperty) bool {
	if len(properties) != 1 || properties[0].Name != "facing" {
		return false
	}

	values := properties[0].Values
	return len(values) == 4 && values[0] == "north" && values[1] == "south" && values[2] == "west" && values[3] == "east"
}

func goName(name string) string {
	parts := strings.Split(name, "_")

	for index, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}

		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}

	return strings.Join(parts, "")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)

	os.Exit(1)
}
