// Code generated by cmd/generate-spawns from Minecraft Java 1.21.11; DO NOT EDIT.
package server

import "github.com/coalaura/minicraft/internal/game"

var naturalBiomeSpawns = [game.BiomeCount][naturalCategoryCount][]naturalSpawnEntry{
	game.BiomeBadlands: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeBambooJungle: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeBasaltDeltas: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeBeach: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeBirchForest: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeCherryGrove: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 2, Minimum: 2, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeColdOcean: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntityCod, Weight: 15, Minimum: 3, Maximum: 6, Charge: 0, Budget: 0},
			{Type: game.EntitySalmon, Weight: 15, Minimum: 1, Maximum: 5, Charge: 0, Budget: 0},
		},
	},
	game.BiomeCrimsonForest: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeDarkForest: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeDeepColdOcean: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntityCod, Weight: 15, Minimum: 3, Maximum: 6, Charge: 0, Budget: 0},
			{Type: game.EntitySalmon, Weight: 15, Minimum: 1, Maximum: 5, Charge: 0, Budget: 0},
		},
	},
	game.BiomeDeepDark: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeDeepFrozenOcean: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntitySalmon, Weight: 15, Minimum: 1, Maximum: 5, Charge: 0, Budget: 0},
		},
	},
	game.BiomeDeepLukewarmOcean: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntityCod, Weight: 8, Minimum: 3, Maximum: 6, Charge: 0, Budget: 0},
			{Type: game.EntityPufferfish, Weight: 5, Minimum: 1, Maximum: 3, Charge: 0, Budget: 0},
			{Type: game.EntityTropicalFish, Weight: 25, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
	},
	game.BiomeDeepOcean: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntityCod, Weight: 10, Minimum: 3, Maximum: 6, Charge: 0, Budget: 0},
		},
	},
	game.BiomeDesert: {
		0: {
			{Type: game.EntityZombie, Weight: 19, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 50, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeDripstoneCaves: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeEndBarrens: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeEndHighlands: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeEndMidlands: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeErodedBadlands: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeFlowerForest: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeForest: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeFrozenOcean: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntitySalmon, Weight: 15, Minimum: 1, Maximum: 5, Charge: 0, Budget: 0},
		},
	},
	game.BiomeFrozenPeaks: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeFrozenRiver: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntitySalmon, Weight: 5, Minimum: 1, Maximum: 5, Charge: 0, Budget: 0},
		},
	},
	game.BiomeGrove: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeIceSpikes: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 20, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeJaggedPeaks: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeJungle: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeLukewarmOcean: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntityCod, Weight: 15, Minimum: 3, Maximum: 6, Charge: 0, Budget: 0},
			{Type: game.EntityPufferfish, Weight: 5, Minimum: 1, Maximum: 3, Charge: 0, Budget: 0},
			{Type: game.EntityTropicalFish, Weight: 25, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
	},
	game.BiomeLushCaves: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntityTropicalFish, Weight: 25, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
	},
	game.BiomeMangroveSwamp: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 70, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntityTropicalFish, Weight: 25, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
	},
	game.BiomeMeadow: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 2, Minimum: 2, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeMushroomFields: {
		0: {},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeNetherWastes: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeOcean: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntityCod, Weight: 10, Minimum: 3, Maximum: 6, Charge: 0, Budget: 0},
		},
	},
	game.BiomeOldGrowthBirchForest: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeOldGrowthPineTaiga: {
		0: {
			{Type: game.EntityZombie, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeOldGrowthSpruceTaiga: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomePaleGarden: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomePlains: {
		0: {
			{Type: game.EntityZombie, Weight: 90, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeRiver: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntitySalmon, Weight: 5, Minimum: 1, Maximum: 5, Charge: 0, Budget: 0},
		},
	},
	game.BiomeSavanna: {
		0: {
			{Type: game.EntityZombie, Weight: 90, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeSavannaPlateau: {
		0: {
			{Type: game.EntityZombie, Weight: 90, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeSmallEndIslands: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeSnowyBeach: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeSnowyPlains: {
		0: {
			{Type: game.EntityZombie, Weight: 90, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 20, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeSnowySlopes: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeSnowyTaiga: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeSoulSandValley: {
		0: {
			{Type: game.EntitySkeleton, Weight: 20, Minimum: 5, Maximum: 5, Charge: 0.7, Budget: 0.15},
		},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeSparseJungle: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeStonyPeaks: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeStonyShore: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeSunflowerPlains: {
		0: {
			{Type: game.EntityZombie, Weight: 90, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeSwamp: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 70, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeTaiga: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeTheEnd: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeTheVoid: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeWarmOcean: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {
			{Type: game.EntityPufferfish, Weight: 15, Minimum: 1, Maximum: 3, Charge: 0, Budget: 0},
			{Type: game.EntityTropicalFish, Weight: 25, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
	},
	game.BiomeWarpedForest: {
		0: {},
		1: {},
		2: {},
		3: {},
	},
	game.BiomeWindsweptForest: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeWindsweptGravellyHills: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeWindsweptHills: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeWindsweptSavanna: {
		0: {
			{Type: game.EntityZombie, Weight: 90, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
	game.BiomeWoodedBadlands: {
		0: {
			{Type: game.EntityZombie, Weight: 95, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntitySkeleton, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCreeper, Weight: 100, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		1: {
			{Type: game.EntitySheep, Weight: 12, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityChicken, Weight: 10, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
			{Type: game.EntityCow, Weight: 8, Minimum: 4, Maximum: 4, Charge: 0, Budget: 0},
		},
		2: {
			{Type: game.EntityBat, Weight: 10, Minimum: 8, Maximum: 8, Charge: 0, Budget: 0},
		},
		3: {},
	},
}

var naturalWarmFarmBiomes = [game.BiomeCount]bool{
	game.BiomeBadlands:          true,
	game.BiomeBambooJungle:      true,
	game.BiomeBasaltDeltas:      true,
	game.BiomeCrimsonForest:     true,
	game.BiomeDeepLukewarmOcean: true,
	game.BiomeDesert:            true,
	game.BiomeErodedBadlands:    true,
	game.BiomeJungle:            true,
	game.BiomeLukewarmOcean:     true,
	game.BiomeMangroveSwamp:     true,
	game.BiomeNetherWastes:      true,
	game.BiomeSavanna:           true,
	game.BiomeSavannaPlateau:    true,
	game.BiomeSoulSandValley:    true,
	game.BiomeSparseJungle:      true,
	game.BiomeWarmOcean:         true,
	game.BiomeWarpedForest:      true,
	game.BiomeWindsweptSavanna:  true,
	game.BiomeWoodedBadlands:    true,
}

var naturalColdFarmBiomes = [game.BiomeCount]bool{
	game.BiomeColdOcean:              true,
	game.BiomeDeepColdOcean:          true,
	game.BiomeDeepDark:               true,
	game.BiomeDeepFrozenOcean:        true,
	game.BiomeEndBarrens:             true,
	game.BiomeEndHighlands:           true,
	game.BiomeEndMidlands:            true,
	game.BiomeFrozenOcean:            true,
	game.BiomeFrozenPeaks:            true,
	game.BiomeFrozenRiver:            true,
	game.BiomeGrove:                  true,
	game.BiomeIceSpikes:              true,
	game.BiomeJaggedPeaks:            true,
	game.BiomeOldGrowthPineTaiga:     true,
	game.BiomeOldGrowthSpruceTaiga:   true,
	game.BiomeSmallEndIslands:        true,
	game.BiomeSnowyBeach:             true,
	game.BiomeSnowyPlains:            true,
	game.BiomeSnowySlopes:            true,
	game.BiomeSnowyTaiga:             true,
	game.BiomeStonyPeaks:             true,
	game.BiomeTaiga:                  true,
	game.BiomeTheEnd:                 true,
	game.BiomeWindsweptForest:        true,
	game.BiomeWindsweptGravellyHills: true,
	game.BiomeWindsweptHills:         true,
}

var naturalTropicalAnyHeightBiomes = [game.BiomeCount]bool{
	game.BiomeLushCaves: true,
}
