// Code generated by cmd/generate-biomes; DO NOT EDIT.

package game

const (
	BiomeBadlands               Biome = 0
	BiomeBambooJungle           Biome = 1
	BiomeBasaltDeltas           Biome = 2
	BiomeBeach                  Biome = 3
	BiomeBirchForest            Biome = 4
	BiomeCherryGrove            Biome = 5
	BiomeColdOcean              Biome = 6
	BiomeCrimsonForest          Biome = 7
	BiomeDarkForest             Biome = 8
	BiomeDeepColdOcean          Biome = 9
	BiomeDeepDark               Biome = 10
	BiomeDeepFrozenOcean        Biome = 11
	BiomeDeepLukewarmOcean      Biome = 12
	BiomeDeepOcean              Biome = 13
	BiomeDesert                 Biome = 14
	BiomeDripstoneCaves         Biome = 15
	BiomeEndBarrens             Biome = 16
	BiomeEndHighlands           Biome = 17
	BiomeEndMidlands            Biome = 18
	BiomeErodedBadlands         Biome = 19
	BiomeFlowerForest           Biome = 20
	BiomeForest                 Biome = 21
	BiomeFrozenOcean            Biome = 22
	BiomeFrozenPeaks            Biome = 23
	BiomeFrozenRiver            Biome = 24
	BiomeGrove                  Biome = 25
	BiomeIceSpikes              Biome = 26
	BiomeJaggedPeaks            Biome = 27
	BiomeJungle                 Biome = 28
	BiomeLukewarmOcean          Biome = 29
	BiomeLushCaves              Biome = 30
	BiomeMangroveSwamp          Biome = 31
	BiomeMeadow                 Biome = 32
	BiomeMushroomFields         Biome = 33
	BiomeNetherWastes           Biome = 34
	BiomeOcean                  Biome = 35
	BiomeOldGrowthBirchForest   Biome = 36
	BiomeOldGrowthPineTaiga     Biome = 37
	BiomeOldGrowthSpruceTaiga   Biome = 38
	BiomePaleGarden             Biome = 39
	BiomePlains                 Biome = 40
	BiomeRiver                  Biome = 41
	BiomeSavanna                Biome = 42
	BiomeSavannaPlateau         Biome = 43
	BiomeSmallEndIslands        Biome = 44
	BiomeSnowyBeach             Biome = 45
	BiomeSnowyPlains            Biome = 46
	BiomeSnowySlopes            Biome = 47
	BiomeSnowyTaiga             Biome = 48
	BiomeSoulSandValley         Biome = 49
	BiomeSparseJungle           Biome = 50
	BiomeStonyPeaks             Biome = 51
	BiomeStonyShore             Biome = 52
	BiomeSunflowerPlains        Biome = 53
	BiomeSwamp                  Biome = 54
	BiomeTaiga                  Biome = 55
	BiomeTheEnd                 Biome = 56
	BiomeTheVoid                Biome = 57
	BiomeWarmOcean              Biome = 58
	BiomeWarpedForest           Biome = 59
	BiomeWindsweptForest        Biome = 60
	BiomeWindsweptGravellyHills Biome = 61
	BiomeWindsweptHills         Biome = 62
	BiomeWindsweptSavanna       Biome = 63
	BiomeWoodedBadlands         Biome = 64

	BiomeCount Biome = 65
)

var BiomeNames = [...]string{
	"badlands",
	"bamboo_jungle",
	"basalt_deltas",
	"beach",
	"birch_forest",
	"cherry_grove",
	"cold_ocean",
	"crimson_forest",
	"dark_forest",
	"deep_cold_ocean",
	"deep_dark",
	"deep_frozen_ocean",
	"deep_lukewarm_ocean",
	"deep_ocean",
	"desert",
	"dripstone_caves",
	"end_barrens",
	"end_highlands",
	"end_midlands",
	"eroded_badlands",
	"flower_forest",
	"forest",
	"frozen_ocean",
	"frozen_peaks",
	"frozen_river",
	"grove",
	"ice_spikes",
	"jagged_peaks",
	"jungle",
	"lukewarm_ocean",
	"lush_caves",
	"mangrove_swamp",
	"meadow",
	"mushroom_fields",
	"nether_wastes",
	"ocean",
	"old_growth_birch_forest",
	"old_growth_pine_taiga",
	"old_growth_spruce_taiga",
	"pale_garden",
	"plains",
	"river",
	"savanna",
	"savanna_plateau",
	"small_end_islands",
	"snowy_beach",
	"snowy_plains",
	"snowy_slopes",
	"snowy_taiga",
	"soul_sand_valley",
	"sparse_jungle",
	"stony_peaks",
	"stony_shore",
	"sunflower_plains",
	"swamp",
	"taiga",
	"the_end",
	"the_void",
	"warm_ocean",
	"warped_forest",
	"windswept_forest",
	"windswept_gravelly_hills",
	"windswept_hills",
	"windswept_savanna",
	"wooded_badlands",
}
