// Code generated by cmd/generate-entities; DO NOT EDIT.

package game

const MaxEntityType EntityType = 156

const (
	EntityAcaciaBoat           EntityType = 0
	EntityAcaciaChestBoat      EntityType = 1
	EntityAllay                EntityType = 2
	EntityAreaEffectCloud      EntityType = 3
	EntityArmadillo            EntityType = 4
	EntityArmorStand           EntityType = 5
	EntityArrow                EntityType = 6
	EntityAxolotl              EntityType = 7
	EntityBambooChestRaft      EntityType = 8
	EntityBambooRaft           EntityType = 9
	EntityBat                  EntityType = 10
	EntityBee                  EntityType = 11
	EntityBirchBoat            EntityType = 12
	EntityBirchChestBoat       EntityType = 13
	EntityBlaze                EntityType = 14
	EntityBlockDisplay         EntityType = 15
	EntityBogged               EntityType = 16
	EntityBreeze               EntityType = 17
	EntityBreezeWindCharge     EntityType = 18
	EntityCamel                EntityType = 19
	EntityCamelHusk            EntityType = 20
	EntityCat                  EntityType = 21
	EntityCaveSpider           EntityType = 22
	EntityCherryBoat           EntityType = 23
	EntityCherryChestBoat      EntityType = 24
	EntityChestMinecart        EntityType = 25
	EntityChicken              EntityType = 26
	EntityCod                  EntityType = 27
	EntityCopperGolem          EntityType = 28
	EntityCommandBlockMinecart EntityType = 29
	EntityCow                  EntityType = 30
	EntityCreaking             EntityType = 31
	EntityCreeper              EntityType = 32
	EntityDarkOakBoat          EntityType = 33
	EntityDarkOakChestBoat     EntityType = 34
	EntityDolphin              EntityType = 35
	EntityDonkey               EntityType = 36
	EntityDragonFireball       EntityType = 37
	EntityDrowned              EntityType = 38
	EntityEgg                  EntityType = 39
	EntityElderGuardian        EntityType = 40
	EntityEnderman             EntityType = 41
	EntityEndermite            EntityType = 42
	EntityEnderDragon          EntityType = 43
	EntityEnderPearl           EntityType = 44
	EntityEndCrystal           EntityType = 45
	EntityEvoker               EntityType = 46
	EntityEvokerFangs          EntityType = 47
	EntityExperienceBottle     EntityType = 48
	EntityExperienceOrb        EntityType = 49
	EntityEyeOfEnder           EntityType = 50
	EntityFallingBlock         EntityType = 51
	EntityFireball             EntityType = 52
	EntityFireworkRocket       EntityType = 53
	EntityFox                  EntityType = 54
	EntityFrog                 EntityType = 55
	EntityFurnaceMinecart      EntityType = 56
	EntityGhast                EntityType = 57
	EntityHappyGhast           EntityType = 58
	EntityGiant                EntityType = 59
	EntityGlowItemFrame        EntityType = 60
	EntityGlowSquid            EntityType = 61
	EntityGoat                 EntityType = 62
	EntityGuardian             EntityType = 63
	EntityHoglin               EntityType = 64
	EntityHopperMinecart       EntityType = 65
	EntityHorse                EntityType = 66
	EntityHusk                 EntityType = 67
	EntityIllusioner           EntityType = 68
	EntityInteraction          EntityType = 69
	EntityIronGolem            EntityType = 70
	EntityItem                 EntityType = 71
	EntityItemDisplay          EntityType = 72
	EntityItemFrame            EntityType = 73
	EntityJungleBoat           EntityType = 74
	EntityJungleChestBoat      EntityType = 75
	EntityLeashKnot            EntityType = 76
	EntityLightningBolt        EntityType = 77
	EntityLlama                EntityType = 78
	EntityLlamaSpit            EntityType = 79
	EntityMagmaCube            EntityType = 80
	EntityMangroveBoat         EntityType = 81
	EntityMangroveChestBoat    EntityType = 82
	EntityMannequin            EntityType = 83
	EntityMarker               EntityType = 84
	EntityMinecart             EntityType = 85
	EntityMooshroom            EntityType = 86
	EntityMule                 EntityType = 87
	EntityNautilus             EntityType = 88
	EntityOakBoat              EntityType = 89
	EntityOakChestBoat         EntityType = 90
	EntityOcelot               EntityType = 91
	EntityOminousItemSpawner   EntityType = 92
	EntityPainting             EntityType = 93
	EntityPaleOakBoat          EntityType = 94
	EntityPaleOakChestBoat     EntityType = 95
	EntityPanda                EntityType = 96
	EntityParched              EntityType = 97
	EntityParrot               EntityType = 98
	EntityPhantom              EntityType = 99
	EntityPig                  EntityType = 100
	EntityPiglin               EntityType = 101
	EntityPiglinBrute          EntityType = 102
	EntityPillager             EntityType = 103
	EntityPolarBear            EntityType = 104
	EntitySplashPotion         EntityType = 105
	EntityLingeringPotion      EntityType = 106
	EntityPufferfish           EntityType = 107
	EntityRabbit               EntityType = 108
	EntityRavager              EntityType = 109
	EntitySalmon               EntityType = 110
	EntitySheep                EntityType = 111
	EntityShulker              EntityType = 112
	EntityShulkerBullet        EntityType = 113
	EntitySilverfish           EntityType = 114
	EntitySkeleton             EntityType = 115
	EntitySkeletonHorse        EntityType = 116
	EntitySlime                EntityType = 117
	EntitySmallFireball        EntityType = 118
	EntitySniffer              EntityType = 119
	EntitySnowball             EntityType = 120
	EntitySnowGolem            EntityType = 121
	EntitySpawnerMinecart      EntityType = 122
	EntitySpectralArrow        EntityType = 123
	EntitySpider               EntityType = 124
	EntitySpruceBoat           EntityType = 125
	EntitySpruceChestBoat      EntityType = 126
	EntitySquid                EntityType = 127
	EntityStray                EntityType = 128
	EntityStrider              EntityType = 129
	EntityTadpole              EntityType = 130
	EntityTextDisplay          EntityType = 131
	EntityTnt                  EntityType = 132
	EntityTntMinecart          EntityType = 133
	EntityTraderLlama          EntityType = 134
	EntityTrident              EntityType = 135
	EntityTropicalFish         EntityType = 136
	EntityTurtle               EntityType = 137
	EntityVex                  EntityType = 138
	EntityVillager             EntityType = 139
	EntityVindicator           EntityType = 140
	EntityWanderingTrader      EntityType = 141
	EntityWarden               EntityType = 142
	EntityWindCharge           EntityType = 143
	EntityWitch                EntityType = 144
	EntityWither               EntityType = 145
	EntityWitherSkeleton       EntityType = 146
	EntityWitherSkull          EntityType = 147
	EntityWolf                 EntityType = 148
	EntityZoglin               EntityType = 149
	EntityZombie               EntityType = 150
	EntityZombieHorse          EntityType = 151
	EntityZombieNautilus       EntityType = 152
	EntityZombieVillager       EntityType = 153
	EntityZombifiedPiglin      EntityType = 154
	EntityPlayer               EntityType = 155
	EntityFishingBobber        EntityType = 156
)

var entityDefinitions = [...]EntityDefinition{
	{ID: EntityAcaciaBoat, Name: "acacia_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityAcaciaChestBoat, Name: "acacia_chest_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityAllay, Name: "allay", Kind: EntityKindMob, Category: EntityCategoryPassiveMobs, Width: 0.35, Height: 0.6},
	{ID: EntityAreaEffectCloud, Name: "area_effect_cloud", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 6, Height: 0.5},
	{ID: EntityArmadillo, Name: "armadillo", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.7, Height: 0.65},
	{ID: EntityArmorStand, Name: "armor_stand", Kind: EntityKindLiving, Category: EntityCategoryImmobile, Width: 0.5, Height: 1.975},
	{ID: EntityArrow, Name: "arrow", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.5, Height: 0.5},
	{ID: EntityAxolotl, Name: "axolotl", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.75, Height: 0.42},
	{ID: EntityBambooChestRaft, Name: "bamboo_chest_raft", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityBambooRaft, Name: "bamboo_raft", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityBat, Name: "bat", Kind: EntityKindAmbient, Category: EntityCategoryUnknown, Width: 0.5, Height: 0.9},
	{ID: EntityBee, Name: "bee", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.7, Height: 0.6},
	{ID: EntityBirchBoat, Name: "birch_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityBirchChestBoat, Name: "birch_chest_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityBlaze, Name: "blaze", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.8},
	{ID: EntityBlockDisplay, Name: "block_display", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0, Height: 0},
	{ID: EntityBogged, Name: "bogged", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.99},
	{ID: EntityBreeze, Name: "breeze", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.77},
	{ID: EntityBreezeWindCharge, Name: "breeze_wind_charge", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.3125, Height: 0.3125},
	{ID: EntityCamel, Name: "camel", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.7, Height: 2.375},
	{ID: EntityCamelHusk, Name: "camel_husk", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.7, Height: 2.375},
	{ID: EntityCat, Name: "cat", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.6, Height: 0.7},
	{ID: EntityCaveSpider, Name: "cave_spider", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.7, Height: 0.5},
	{ID: EntityCherryBoat, Name: "cherry_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityCherryChestBoat, Name: "cherry_chest_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityChestMinecart, Name: "chest_minecart", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 0.98, Height: 0.7},
	{ID: EntityChicken, Name: "chicken", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.4, Height: 0.7},
	{ID: EntityCod, Name: "cod", Kind: EntityKindMob, Category: EntityCategoryPassiveMobs, Width: 0.5, Height: 0.3},
	{ID: EntityCopperGolem, Name: "copper_golem", Kind: EntityKindMob, Category: EntityCategoryPassiveMobs, Width: 0.49, Height: 0.98},
	{ID: EntityCommandBlockMinecart, Name: "command_block_minecart", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 0.98, Height: 0.7},
	{ID: EntityCow, Name: "cow", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.9, Height: 1.4},
	{ID: EntityCreaking, Name: "creaking", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.9, Height: 2.7},
	{ID: EntityCreeper, Name: "creeper", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.7},
	{ID: EntityDarkOakBoat, Name: "dark_oak_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityDarkOakChestBoat, Name: "dark_oak_chest_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityDolphin, Name: "dolphin", Kind: EntityKindPassive, Category: EntityCategoryPassiveMobs, Width: 0.9, Height: 0.6},
	{ID: EntityDonkey, Name: "donkey", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.3964844, Height: 1.5},
	{ID: EntityDragonFireball, Name: "dragon_fireball", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 1, Height: 1},
	{ID: EntityDrowned, Name: "drowned", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityEgg, Name: "egg", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
	{ID: EntityElderGuardian, Name: "elder_guardian", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 1.9975, Height: 1.9975},
	{ID: EntityEnderman, Name: "enderman", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 2.9},
	{ID: EntityEndermite, Name: "endermite", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.4, Height: 0.3},
	{ID: EntityEnderDragon, Name: "ender_dragon", Kind: EntityKindMob, Category: EntityCategoryHostileMobs, Width: 16, Height: 8},
	{ID: EntityEnderPearl, Name: "ender_pearl", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
	{ID: EntityEndCrystal, Name: "end_crystal", Kind: EntityKindOther, Category: EntityCategoryHostileMobs, Width: 2, Height: 2},
	{ID: EntityEvoker, Name: "evoker", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityEvokerFangs, Name: "evoker_fangs", Kind: EntityKindOther, Category: EntityCategoryProjectiles, Width: 0.5, Height: 0.8},
	{ID: EntityExperienceBottle, Name: "experience_bottle", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
	{ID: EntityExperienceOrb, Name: "experience_orb", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0.5, Height: 0.5},
	{ID: EntityEyeOfEnder, Name: "eye_of_ender", Kind: EntityKindOther, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
	{ID: EntityFallingBlock, Name: "falling_block", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0.98, Height: 0.98},
	{ID: EntityFireball, Name: "fireball", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 1, Height: 1},
	{ID: EntityFireworkRocket, Name: "firework_rocket", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
	{ID: EntityFox, Name: "fox", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.6, Height: 0.7},
	{ID: EntityFrog, Name: "frog", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.5, Height: 0.5},
	{ID: EntityFurnaceMinecart, Name: "furnace_minecart", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 0.98, Height: 0.7},
	{ID: EntityGhast, Name: "ghast", Kind: EntityKindMob, Category: EntityCategoryHostileMobs, Width: 4, Height: 4},
	{ID: EntityHappyGhast, Name: "happy_ghast", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 4, Height: 4},
	{ID: EntityGiant, Name: "giant", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 3.6, Height: 12},
	{ID: EntityGlowItemFrame, Name: "glow_item_frame", Kind: EntityKindOther, Category: EntityCategoryImmobile, Width: 0.5, Height: 0.5},
	{ID: EntityGlowSquid, Name: "glow_squid", Kind: EntityKindPassive, Category: EntityCategoryPassiveMobs, Width: 0.8, Height: 0.8},
	{ID: EntityGoat, Name: "goat", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.9, Height: 1.3},
	{ID: EntityGuardian, Name: "guardian", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.85, Height: 0.85},
	{ID: EntityHoglin, Name: "hoglin", Kind: EntityKindAnimal, Category: EntityCategoryHostileMobs, Width: 1.3964844, Height: 1.4},
	{ID: EntityHopperMinecart, Name: "hopper_minecart", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 0.98, Height: 0.7},
	{ID: EntityHorse, Name: "horse", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.3964844, Height: 1.6},
	{ID: EntityHusk, Name: "husk", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityIllusioner, Name: "illusioner", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityInteraction, Name: "interaction", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0, Height: 0},
	{ID: EntityIronGolem, Name: "iron_golem", Kind: EntityKindMob, Category: EntityCategoryPassiveMobs, Width: 1.4, Height: 2.7},
	{ID: EntityItem, Name: "item", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0.25, Height: 0.25},
	{ID: EntityItemDisplay, Name: "item_display", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0, Height: 0},
	{ID: EntityItemFrame, Name: "item_frame", Kind: EntityKindOther, Category: EntityCategoryImmobile, Width: 0.5, Height: 0.5},
	{ID: EntityJungleBoat, Name: "jungle_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityJungleChestBoat, Name: "jungle_chest_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityLeashKnot, Name: "leash_knot", Kind: EntityKindOther, Category: EntityCategoryImmobile, Width: 0.375, Height: 0.5},
	{ID: EntityLightningBolt, Name: "lightning_bolt", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0, Height: 0},
	{ID: EntityLlama, Name: "llama", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.9, Height: 1.87},
	{ID: EntityLlamaSpit, Name: "llama_spit", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
	{ID: EntityMagmaCube, Name: "magma_cube", Kind: EntityKindMob, Category: EntityCategoryHostileMobs, Width: 0.52, Height: 0.52},
	{ID: EntityMangroveBoat, Name: "mangrove_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityMangroveChestBoat, Name: "mangrove_chest_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityMannequin, Name: "mannequin", Kind: EntityKindLiving, Category: EntityCategoryImmobile, Width: 0.6, Height: 1.8},
	{ID: EntityMarker, Name: "marker", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0, Height: 0},
	{ID: EntityMinecart, Name: "minecart", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 0.98, Height: 0.7},
	{ID: EntityMooshroom, Name: "mooshroom", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.9, Height: 1.4},
	{ID: EntityMule, Name: "mule", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.3964844, Height: 1.6},
	{ID: EntityNautilus, Name: "nautilus", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.875, Height: 0.95},
	{ID: EntityOakBoat, Name: "oak_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityOakChestBoat, Name: "oak_chest_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityOcelot, Name: "ocelot", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.6, Height: 0.7},
	{ID: EntityOminousItemSpawner, Name: "ominous_item_spawner", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0.25, Height: 0.25},
	{ID: EntityPainting, Name: "painting", Kind: EntityKindOther, Category: EntityCategoryImmobile, Width: 0.5, Height: 0.5},
	{ID: EntityPaleOakBoat, Name: "pale_oak_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityPaleOakChestBoat, Name: "pale_oak_chest_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntityPanda, Name: "panda", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.3, Height: 1.25},
	{ID: EntityParched, Name: "parched", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.99},
	{ID: EntityParrot, Name: "parrot", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.5, Height: 0.9},
	{ID: EntityPhantom, Name: "phantom", Kind: EntityKindMob, Category: EntityCategoryHostileMobs, Width: 0.9, Height: 0.5},
	{ID: EntityPig, Name: "pig", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.9, Height: 0.9},
	{ID: EntityPiglin, Name: "piglin", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityPiglinBrute, Name: "piglin_brute", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityPillager, Name: "pillager", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityPolarBear, Name: "polar_bear", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.4, Height: 1.4},
	{ID: EntitySplashPotion, Name: "splash_potion", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
	{ID: EntityLingeringPotion, Name: "lingering_potion", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
	{ID: EntityPufferfish, Name: "pufferfish", Kind: EntityKindMob, Category: EntityCategoryPassiveMobs, Width: 0.7, Height: 0.7},
	{ID: EntityRabbit, Name: "rabbit", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.4, Height: 0.5},
	{ID: EntityRavager, Name: "ravager", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 1.95, Height: 2.2},
	{ID: EntitySalmon, Name: "salmon", Kind: EntityKindMob, Category: EntityCategoryPassiveMobs, Width: 0.7, Height: 0.4},
	{ID: EntitySheep, Name: "sheep", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.9, Height: 1.3},
	{ID: EntityShulker, Name: "shulker", Kind: EntityKindMob, Category: EntityCategoryHostileMobs, Width: 1, Height: 1},
	{ID: EntityShulkerBullet, Name: "shulker_bullet", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.3125, Height: 0.3125},
	{ID: EntitySilverfish, Name: "silverfish", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.4, Height: 0.3},
	{ID: EntitySkeleton, Name: "skeleton", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.99},
	{ID: EntitySkeletonHorse, Name: "skeleton_horse", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.3964844, Height: 1.6},
	{ID: EntitySlime, Name: "slime", Kind: EntityKindMob, Category: EntityCategoryHostileMobs, Width: 0.52, Height: 0.52},
	{ID: EntitySmallFireball, Name: "small_fireball", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.3125, Height: 0.3125},
	{ID: EntitySniffer, Name: "sniffer", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.9, Height: 1.75},
	{ID: EntitySnowball, Name: "snowball", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
	{ID: EntitySnowGolem, Name: "snow_golem", Kind: EntityKindMob, Category: EntityCategoryPassiveMobs, Width: 0.7, Height: 1.9},
	{ID: EntitySpawnerMinecart, Name: "spawner_minecart", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 0.98, Height: 0.7},
	{ID: EntitySpectralArrow, Name: "spectral_arrow", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.5, Height: 0.5},
	{ID: EntitySpider, Name: "spider", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 1.4, Height: 0.9},
	{ID: EntitySpruceBoat, Name: "spruce_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntitySpruceChestBoat, Name: "spruce_chest_boat", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 1.375, Height: 0.5625},
	{ID: EntitySquid, Name: "squid", Kind: EntityKindPassive, Category: EntityCategoryPassiveMobs, Width: 0.8, Height: 0.8},
	{ID: EntityStray, Name: "stray", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.99},
	{ID: EntityStrider, Name: "strider", Kind: EntityKindAnimal, Category: EntityCategoryHostileMobs, Width: 0.9, Height: 1.7},
	{ID: EntityTadpole, Name: "tadpole", Kind: EntityKindMob, Category: EntityCategoryPassiveMobs, Width: 0.4, Height: 0.3},
	{ID: EntityTextDisplay, Name: "text_display", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0, Height: 0},
	{ID: EntityTnt, Name: "tnt", Kind: EntityKindOther, Category: EntityCategoryUnknown, Width: 0.98, Height: 0.98},
	{ID: EntityTntMinecart, Name: "tnt_minecart", Kind: EntityKindOther, Category: EntityCategoryVehicles, Width: 0.98, Height: 0.7},
	{ID: EntityTraderLlama, Name: "trader_llama", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.9, Height: 1.87},
	{ID: EntityTrident, Name: "trident", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.5, Height: 0.5},
	{ID: EntityTropicalFish, Name: "tropical_fish", Kind: EntityKindMob, Category: EntityCategoryPassiveMobs, Width: 0.5, Height: 0.4},
	{ID: EntityTurtle, Name: "turtle", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.2, Height: 0.4},
	{ID: EntityVex, Name: "vex", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.4, Height: 0.8},
	{ID: EntityVillager, Name: "villager", Kind: EntityKindPassive, Category: EntityCategoryUnknown, Width: 0.6, Height: 1.95},
	{ID: EntityVindicator, Name: "vindicator", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityWanderingTrader, Name: "wandering_trader", Kind: EntityKindPassive, Category: EntityCategoryUnknown, Width: 0.6, Height: 1.95},
	{ID: EntityWarden, Name: "warden", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.9, Height: 2.9},
	{ID: EntityWindCharge, Name: "wind_charge", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.3125, Height: 0.3125},
	{ID: EntityWitch, Name: "witch", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityWither, Name: "wither", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.9, Height: 3.5},
	{ID: EntityWitherSkeleton, Name: "wither_skeleton", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.7, Height: 2.4},
	{ID: EntityWitherSkull, Name: "wither_skull", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.3125, Height: 0.3125},
	{ID: EntityWolf, Name: "wolf", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.6, Height: 0.85},
	{ID: EntityZoglin, Name: "zoglin", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 1.3964844, Height: 1.4},
	{ID: EntityZombie, Name: "zombie", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityZombieHorse, Name: "zombie_horse", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 1.3964844, Height: 1.6},
	{ID: EntityZombieNautilus, Name: "zombie_nautilus", Kind: EntityKindAnimal, Category: EntityCategoryPassiveMobs, Width: 0.875, Height: 0.95},
	{ID: EntityZombieVillager, Name: "zombie_villager", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityZombifiedPiglin, Name: "zombified_piglin", Kind: EntityKindHostile, Category: EntityCategoryHostileMobs, Width: 0.6, Height: 1.95},
	{ID: EntityPlayer, Name: "player", Kind: EntityKindPlayer, Category: EntityCategoryUnknown, Width: 0.6, Height: 1.8},
	{ID: EntityFishingBobber, Name: "fishing_bobber", Kind: EntityKindProjectile, Category: EntityCategoryProjectiles, Width: 0.25, Height: 0.25},
}
