// Code generated by cmd/generate-mob-effects; DO NOT EDIT.

package game

const MaxMobEffectID MobEffect = 39

const (
	MobEffectSpeed               MobEffect = 0
	MobEffectSlowness            MobEffect = 1
	MobEffectHaste               MobEffect = 2
	MobEffectMiningFatigue       MobEffect = 3
	MobEffectStrength            MobEffect = 4
	MobEffectInstantHealth       MobEffect = 5
	MobEffectInstantDamage       MobEffect = 6
	MobEffectJumpBoost           MobEffect = 7
	MobEffectNausea              MobEffect = 8
	MobEffectRegeneration        MobEffect = 9
	MobEffectResistance          MobEffect = 10
	MobEffectFireResistance      MobEffect = 11
	MobEffectWaterBreathing      MobEffect = 12
	MobEffectInvisibility        MobEffect = 13
	MobEffectBlindness           MobEffect = 14
	MobEffectNightVision         MobEffect = 15
	MobEffectHunger              MobEffect = 16
	MobEffectWeakness            MobEffect = 17
	MobEffectPoison              MobEffect = 18
	MobEffectWither              MobEffect = 19
	MobEffectHealthBoost         MobEffect = 20
	MobEffectAbsorption          MobEffect = 21
	MobEffectSaturation          MobEffect = 22
	MobEffectGlowing             MobEffect = 23
	MobEffectLevitation          MobEffect = 24
	MobEffectLuck                MobEffect = 25
	MobEffectUnluck              MobEffect = 26
	MobEffectSlowFalling         MobEffect = 27
	MobEffectConduitPower        MobEffect = 28
	MobEffectDolphinsGrace       MobEffect = 29
	MobEffectBadOmen             MobEffect = 30
	MobEffectHeroOfTheVillage    MobEffect = 31
	MobEffectDarkness            MobEffect = 32
	MobEffectTrialOmen           MobEffect = 33
	MobEffectRaidOmen            MobEffect = 34
	MobEffectWindCharged         MobEffect = 35
	MobEffectWeaving             MobEffect = 36
	MobEffectOozing              MobEffect = 37
	MobEffectInfested            MobEffect = 38
	MobEffectBreathOfTheNautilus MobEffect = 39
)

var generatedMobEffectDefinitions = [...]MobEffectDefinition{
	{ID: MobEffectSpeed, Name: "speed"},
	{ID: MobEffectSlowness, Name: "slowness"},
	{ID: MobEffectHaste, Name: "haste"},
	{ID: MobEffectMiningFatigue, Name: "mining_fatigue"},
	{ID: MobEffectStrength, Name: "strength"},
	{ID: MobEffectInstantHealth, Name: "instant_health"},
	{ID: MobEffectInstantDamage, Name: "instant_damage"},
	{ID: MobEffectJumpBoost, Name: "jump_boost"},
	{ID: MobEffectNausea, Name: "nausea"},
	{ID: MobEffectRegeneration, Name: "regeneration"},
	{ID: MobEffectResistance, Name: "resistance"},
	{ID: MobEffectFireResistance, Name: "fire_resistance"},
	{ID: MobEffectWaterBreathing, Name: "water_breathing"},
	{ID: MobEffectInvisibility, Name: "invisibility"},
	{ID: MobEffectBlindness, Name: "blindness"},
	{ID: MobEffectNightVision, Name: "night_vision"},
	{ID: MobEffectHunger, Name: "hunger"},
	{ID: MobEffectWeakness, Name: "weakness"},
	{ID: MobEffectPoison, Name: "poison"},
	{ID: MobEffectWither, Name: "wither"},
	{ID: MobEffectHealthBoost, Name: "health_boost"},
	{ID: MobEffectAbsorption, Name: "absorption"},
	{ID: MobEffectSaturation, Name: "saturation"},
	{ID: MobEffectGlowing, Name: "glowing"},
	{ID: MobEffectLevitation, Name: "levitation"},
	{ID: MobEffectLuck, Name: "luck"},
	{ID: MobEffectUnluck, Name: "unluck"},
	{ID: MobEffectSlowFalling, Name: "slow_falling"},
	{ID: MobEffectConduitPower, Name: "conduit_power"},
	{ID: MobEffectDolphinsGrace, Name: "dolphins_grace"},
	{ID: MobEffectBadOmen, Name: "bad_omen"},
	{ID: MobEffectHeroOfTheVillage, Name: "hero_of_the_village"},
	{ID: MobEffectDarkness, Name: "darkness"},
	{ID: MobEffectTrialOmen, Name: "trial_omen"},
	{ID: MobEffectRaidOmen, Name: "raid_omen"},
	{ID: MobEffectWindCharged, Name: "wind_charged"},
	{ID: MobEffectWeaving, Name: "weaving"},
	{ID: MobEffectOozing, Name: "oozing"},
	{ID: MobEffectInfested, Name: "infested"},
	{ID: MobEffectBreathOfTheNautilus, Name: "breath_of_the_nautilus"},
}
