// Code generated by cmd/generate-potions; DO NOT EDIT.

package game

const (
	PotionWater              Potion = 0
	PotionMundane            Potion = 1
	PotionThick              Potion = 2
	PotionAwkward            Potion = 3
	PotionNightVision        Potion = 4
	PotionLongNightVision    Potion = 5
	PotionInvisibility       Potion = 6
	PotionLongInvisibility   Potion = 7
	PotionLeaping            Potion = 8
	PotionLongLeaping        Potion = 9
	PotionStrongLeaping      Potion = 10
	PotionFireResistance     Potion = 11
	PotionLongFireResistance Potion = 12
	PotionSwiftness          Potion = 13
	PotionLongSwiftness      Potion = 14
	PotionStrongSwiftness    Potion = 15
	PotionSlowness           Potion = 16
	PotionLongSlowness       Potion = 17
	PotionStrongSlowness     Potion = 18
	PotionTurtleMaster       Potion = 19
	PotionLongTurtleMaster   Potion = 20
	PotionStrongTurtleMaster Potion = 21
	PotionWaterBreathing     Potion = 22
	PotionLongWaterBreathing Potion = 23
	PotionHealing            Potion = 24
	PotionStrongHealing      Potion = 25
	PotionHarming            Potion = 26
	PotionStrongHarming      Potion = 27
	PotionPoison             Potion = 28
	PotionLongPoison         Potion = 29
	PotionStrongPoison       Potion = 30
	PotionRegeneration       Potion = 31
	PotionLongRegeneration   Potion = 32
	PotionStrongRegeneration Potion = 33
	PotionStrength           Potion = 34
	PotionLongStrength       Potion = 35
	PotionStrongStrength     Potion = 36
	PotionWeakness           Potion = 37
	PotionLongWeakness       Potion = 38
	PotionLuck               Potion = 39
	PotionSlowFalling        Potion = 40
	PotionLongSlowFalling    Potion = 41
	PotionWindCharged        Potion = 42
	PotionWeaving            Potion = 43
	PotionOozing             Potion = 44
	PotionInfested           Potion = 45
)

var generatedPotionDefinitions = [...]PotionDefinition{
	{Name: "water", Effects: nil},
	{Name: "mundane", Effects: nil},
	{Name: "thick", Effects: nil},
	{Name: "awkward", Effects: nil},
	{Name: "night_vision", Effects: []MobEffectInstance{{Effect: MobEffectNightVision, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_night_vision", Effects: []MobEffectInstance{{Effect: MobEffectNightVision, Duration: 9600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "invisibility", Effects: []MobEffectInstance{{Effect: MobEffectInvisibility, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_invisibility", Effects: []MobEffectInstance{{Effect: MobEffectInvisibility, Duration: 9600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "leaping", Effects: []MobEffectInstance{{Effect: MobEffectJumpBoost, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_leaping", Effects: []MobEffectInstance{{Effect: MobEffectJumpBoost, Duration: 9600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "strong_leaping", Effects: []MobEffectInstance{{Effect: MobEffectJumpBoost, Duration: 1800, Amplifier: 1, Visible: true, ShowIcon: true}}},
	{Name: "fire_resistance", Effects: []MobEffectInstance{{Effect: MobEffectFireResistance, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_fire_resistance", Effects: []MobEffectInstance{{Effect: MobEffectFireResistance, Duration: 9600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "swiftness", Effects: []MobEffectInstance{{Effect: MobEffectSpeed, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_swiftness", Effects: []MobEffectInstance{{Effect: MobEffectSpeed, Duration: 9600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "strong_swiftness", Effects: []MobEffectInstance{{Effect: MobEffectSpeed, Duration: 1800, Amplifier: 1, Visible: true, ShowIcon: true}}},
	{Name: "slowness", Effects: []MobEffectInstance{{Effect: MobEffectSlowness, Duration: 1800, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_slowness", Effects: []MobEffectInstance{{Effect: MobEffectSlowness, Duration: 4800, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "strong_slowness", Effects: []MobEffectInstance{{Effect: MobEffectSlowness, Duration: 400, Amplifier: 3, Visible: true, ShowIcon: true}}},
	{Name: "turtle_master", Effects: []MobEffectInstance{{Effect: MobEffectSlowness, Duration: 400, Amplifier: 3, Visible: true, ShowIcon: true}, {Effect: MobEffectResistance, Duration: 400, Amplifier: 2, Visible: true, ShowIcon: true}}},
	{Name: "long_turtle_master", Effects: []MobEffectInstance{{Effect: MobEffectSlowness, Duration: 800, Amplifier: 3, Visible: true, ShowIcon: true}, {Effect: MobEffectResistance, Duration: 800, Amplifier: 2, Visible: true, ShowIcon: true}}},
	{Name: "strong_turtle_master", Effects: []MobEffectInstance{{Effect: MobEffectSlowness, Duration: 400, Amplifier: 5, Visible: true, ShowIcon: true}, {Effect: MobEffectResistance, Duration: 400, Amplifier: 3, Visible: true, ShowIcon: true}}},
	{Name: "water_breathing", Effects: []MobEffectInstance{{Effect: MobEffectWaterBreathing, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_water_breathing", Effects: []MobEffectInstance{{Effect: MobEffectWaterBreathing, Duration: 9600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "healing", Effects: []MobEffectInstance{{Effect: MobEffectInstantHealth, Duration: 1, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "strong_healing", Effects: []MobEffectInstance{{Effect: MobEffectInstantHealth, Duration: 1, Amplifier: 1, Visible: true, ShowIcon: true}}},
	{Name: "harming", Effects: []MobEffectInstance{{Effect: MobEffectInstantDamage, Duration: 1, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "strong_harming", Effects: []MobEffectInstance{{Effect: MobEffectInstantDamage, Duration: 1, Amplifier: 1, Visible: true, ShowIcon: true}}},
	{Name: "poison", Effects: []MobEffectInstance{{Effect: MobEffectPoison, Duration: 900, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_poison", Effects: []MobEffectInstance{{Effect: MobEffectPoison, Duration: 1800, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "strong_poison", Effects: []MobEffectInstance{{Effect: MobEffectPoison, Duration: 432, Amplifier: 1, Visible: true, ShowIcon: true}}},
	{Name: "regeneration", Effects: []MobEffectInstance{{Effect: MobEffectRegeneration, Duration: 900, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_regeneration", Effects: []MobEffectInstance{{Effect: MobEffectRegeneration, Duration: 1800, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "strong_regeneration", Effects: []MobEffectInstance{{Effect: MobEffectRegeneration, Duration: 450, Amplifier: 1, Visible: true, ShowIcon: true}}},
	{Name: "strength", Effects: []MobEffectInstance{{Effect: MobEffectStrength, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_strength", Effects: []MobEffectInstance{{Effect: MobEffectStrength, Duration: 9600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "strong_strength", Effects: []MobEffectInstance{{Effect: MobEffectStrength, Duration: 1800, Amplifier: 1, Visible: true, ShowIcon: true}}},
	{Name: "weakness", Effects: []MobEffectInstance{{Effect: MobEffectWeakness, Duration: 1800, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_weakness", Effects: []MobEffectInstance{{Effect: MobEffectWeakness, Duration: 4800, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "luck", Effects: []MobEffectInstance{{Effect: MobEffectLuck, Duration: 6000, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "slow_falling", Effects: []MobEffectInstance{{Effect: MobEffectSlowFalling, Duration: 1800, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "long_slow_falling", Effects: []MobEffectInstance{{Effect: MobEffectSlowFalling, Duration: 4800, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "wind_charged", Effects: []MobEffectInstance{{Effect: MobEffectWindCharged, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "weaving", Effects: []MobEffectInstance{{Effect: MobEffectWeaving, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "oozing", Effects: []MobEffectInstance{{Effect: MobEffectOozing, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
	{Name: "infested", Effects: []MobEffectInstance{{Effect: MobEffectInfested, Duration: 3600, Amplifier: 0, Visible: true, ShowIcon: true}}},
}
