package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode"
)

type dataManifest struct {
	Potions []potionDefinition `json:"potions"`
}

type potionEffectDefinition struct {
	Name      string `json:"name"`
	Duration  int32  `json:"duration"`
	Amplifier int32  `json:"amplifier"`
}

type potionDefinition struct {
	Name    string                   `json:"name"`
	Effects []potionEffectDefinition `json:"effects"`
}

func main() {
	manifestPath := flag.String("manifest", "", "source manifest path")
	outputPath := flag.String("output", "", "generated Go output path")

	flag.Parse()

	if *manifestPath == "" || *outputPath == "" {
		fail(fmt.Errorf("manifest and output are required"))
	}

	generated, err := generate(*manifestPath)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*outputPath, generated, 0o644)
	if err != nil {
		fail(err)
	}
}

func generate(manifestPath string) ([]byte, error) {
	manifest, err := readManifest(manifestPath)
	if err != nil {
		return nil, err
	}

	if len(manifest.Potions) != 46 {
		return nil, fmt.Errorf("potion manifest has %d registered potions, want 46", len(manifest.Potions))
	}

	names := make(map[string]struct{}, len(manifest.Potions))

	for index, potion := range manifest.Potions {
		if potion.Name == "" {
			return nil, fmt.Errorf("potion %d has no name", index)
		}

		_, exists := names[potion.Name]
		if exists {
			return nil, fmt.Errorf("potion %q is duplicated", potion.Name)
		}

		names[potion.Name] = struct{}{}

		for _, effect := range potion.Effects {
			if effect.Name == "" || effect.Duration <= 0 || effect.Amplifier < 0 {
				return nil, fmt.Errorf("potion %q has invalid effect values", potion.Name)
			}
		}
	}

	return generateGame(manifest.Potions)
}

func readManifest(path string) (dataManifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return dataManifest{}, err
	}

	var manifest dataManifest

	err = json.Unmarshal(raw, &manifest)
	if err != nil {
		return dataManifest{}, err
	}

	return manifest, nil
}

func generateGame(definitions []potionDefinition) ([]byte, error) {
	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-potions; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package game")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "const (")

	for id, definition := range definitions {
		fmt.Fprintf(&output, "\tPotion%s Potion = %d\n", goName(definition.Name), id)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var generatedPotionDefinitions = [...]PotionDefinition{")

	for _, definition := range definitions {
		fmt.Fprintf(&output, "\t{Name: %q, Effects: %s},\n", definition.Name, effectSlice(definition.Effects))
	}

	fmt.Fprintln(&output, "}")

	return format.Source(output.Bytes())
}

func effectSlice(effects []potionEffectDefinition) string {
	if len(effects) == 0 {
		return "nil"
	}

	values := make([]string, len(effects))

	for index, effect := range effects {
		values[index] = fmt.Sprintf("{Effect: MobEffect%s, Duration: %d, Amplifier: %d, Visible: true, ShowIcon: true}", goName(effect.Name), effect.Duration, effect.Amplifier)
	}

	return "[]MobEffectInstance{" + strings.Join(values, ", ") + "}"
}

func goName(name string) string {
	parts := strings.Split(name, "_")

	for index, part := range parts {
		runes := []rune(part)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
			parts[index] = string(runes)
		}
	}

	return strings.Join(parts, "")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
