package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strings"
	"unicode"
)

type sourceManifest struct {
	Source string `json:"source"`
	SHA256 string `json:"sha256"`
}

type mobEffectDefinition struct {
	Name string
}

func main() {
	manifestPath := flag.String("manifest", "", "source manifest path")
	sourcePath := flag.String("source", "", "MobEffects.java source path")
	outputPath := flag.String("output", "", "generated Go output path")

	flag.Parse()

	if *manifestPath == "" || *sourcePath == "" || *outputPath == "" {
		fail(fmt.Errorf("manifest, source and output are required"))
	}

	generated, err := generate(*manifestPath, *sourcePath)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*outputPath, generated, 0o644)
	if err != nil {
		fail(err)
	}
}

func generate(manifestPath, sourcePath string) ([]byte, error) {
	manifest, err := readManifest(manifestPath)
	if err != nil {
		return nil, err
	}

	source, err := os.ReadFile(sourcePath)
	if err != nil {
		return nil, err
	}

	digest := sha256.Sum256(source)

	actualHash := hex.EncodeToString(digest[:])
	if actualHash != manifest.SHA256 {
		return nil, fmt.Errorf("MobEffects.java SHA-256 = %s, want %s", actualHash, manifest.SHA256)
	}

	definitions := parseDefinitions(source)
	if len(definitions) != 40 {
		return nil, fmt.Errorf("MobEffects.java has %d registered effects, want 40", len(definitions))
	}

	return generateGame(definitions, actualHash)
}

func readManifest(path string) (sourceManifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return sourceManifest{}, err
	}

	var manifest sourceManifest

	err = json.Unmarshal(raw, &manifest)
	if err != nil {
		return sourceManifest{}, err
	}

	if manifest.Source == "" || len(manifest.SHA256) != sha256.Size*2 {
		return sourceManifest{}, fmt.Errorf("invalid MobEffects source manifest")
	}

	return manifest, nil
}

func parseDefinitions(source []byte) []mobEffectDefinition {
	register := regexp.MustCompile(`register\(\s*"([a-z0-9_]+)"`)
	matches := register.FindAllSubmatch(source, -1)

	definitions := make([]mobEffectDefinition, 0, len(matches))

	for _, match := range matches {
		definitions = append(definitions, mobEffectDefinition{Name: string(match[1])})
	}

	return definitions
}

func generateGame(definitions []mobEffectDefinition, sourceHash string) ([]byte, error) {
	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-mob-effects; DO NOT EDIT.")
	fmt.Fprintf(&output, "// Source SHA-256: %s\n", sourceHash)
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package game")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "const MaxMobEffectID MobEffect = %d\n\n", len(definitions)-1)
	fmt.Fprintln(&output, "const (")

	for id, definition := range definitions {
		fmt.Fprintf(&output, "\tMobEffect%s MobEffect = %d\n", goName(definition.Name), id)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var generatedMobEffectDefinitions = [...]MobEffectDefinition{")

	for _, definition := range definitions {
		fmt.Fprintf(&output, "\t{ID: MobEffect%s, Name: %q},\n", goName(definition.Name), definition.Name)
	}

	fmt.Fprintln(&output, "}")

	return format.Source(output.Bytes())
}

func goName(name string) string {
	parts := strings.Split(name, "_")

	for index, part := range parts {
		runes := []rune(part)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
			parts[index] = string(runes)
		}
	}

	return strings.Join(parts, "")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
