package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode"
)

type dataManifest struct {
	Effects []string `json:"effects"`
}

type mobEffectDefinition struct {
	Name string
}

func main() {
	manifestPath := flag.String("manifest", "", "source manifest path")
	outputPath := flag.String("output", "", "generated Go output path")

	flag.Parse()

	if *manifestPath == "" || *outputPath == "" {
		fail(fmt.Errorf("manifest and output are required"))
	}

	generated, err := generate(*manifestPath)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*outputPath, generated, 0o644)
	if err != nil {
		fail(err)
	}
}

func generate(manifestPath string) ([]byte, error) {
	manifest, err := readManifest(manifestPath)
	if err != nil {
		return nil, err
	}

	definitions := make([]mobEffectDefinition, len(manifest.Effects))
	names := make(map[string]struct{}, len(manifest.Effects))

	for index, name := range manifest.Effects {
		if name == "" {
			return nil, fmt.Errorf("mob effect %d has no name", index)
		}

		_, exists := names[name]
		if exists {
			return nil, fmt.Errorf("mob effect %q is duplicated", name)
		}

		names[name] = struct{}{}
		definitions[index] = mobEffectDefinition{Name: name}
	}

	if len(definitions) != 40 {
		return nil, fmt.Errorf("mob effect manifest has %d registered effects, want 40", len(definitions))
	}

	return generateGame(definitions)
}

func readManifest(path string) (dataManifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return dataManifest{}, err
	}

	var manifest dataManifest

	err = json.Unmarshal(raw, &manifest)
	if err != nil {
		return dataManifest{}, err
	}

	return manifest, nil
}

func generateGame(definitions []mobEffectDefinition) ([]byte, error) {
	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-mob-effects; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package game")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "const MaxMobEffectID MobEffect = %d\n\n", len(definitions)-1)
	fmt.Fprintln(&output, "const (")

	for id, definition := range definitions {
		fmt.Fprintf(&output, "\tMobEffect%s MobEffect = %d\n", goName(definition.Name), id)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var generatedMobEffectDefinitions = [...]MobEffectDefinition{")

	for _, definition := range definitions {
		fmt.Fprintf(&output, "\t{ID: MobEffect%s, Name: %q},\n", goName(definition.Name), definition.Name)
	}

	fmt.Fprintln(&output, "}")

	return format.Source(output.Bytes())
}

func goName(name string) string {
	parts := strings.Split(name, "_")

	for index, part := range parts {
		runes := []rune(part)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
			parts[index] = string(runes)
		}
	}

	return strings.Join(parts, "")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
