// Command generate-spawns extracts the supported subset of the pinned vanilla biome data.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/coalaura/minicraft/internal/game"
)

type spawnEntry struct {
	Type    string `json:"type"`
	Weight  int    `json:"weight"`
	Minimum int    `json:"minCount"`
	Maximum int    `json:"maxCount"`
}

type spawnCost struct {
	Charge float64 `json:"charge"`
	Budget float64 `json:"energy_budget"`
}

type biomeData struct {
	Spawners map[string][]spawnEntry `json:"spawners"`
	Costs    map[string]spawnCost    `json:"spawn_costs"`
}

type biomeTag struct {
	Values []string `json:"values"`
}

var supported = map[string]bool{
	"zombie": true, "skeleton": true, "creeper": true, "cow": true, "sheep": true, "chicken": true,
	"bat": true, "cod": true, "salmon": true, "tropical_fish": true, "pufferfish": true,
}

func main() {
	input := flag.String("input", "data/worldgen_biome", "committed pinned biome directory")
	tags := flag.String("tags", "data/biome_tags", "committed pinned biome tags")
	output := flag.String("output", "internal/server/natural_spawn_data_generated.go", "generated Go file")

	flag.Parse()

	var buffer bytes.Buffer

	buffer.WriteString("// Code generated by cmd/generate-spawns from Minecraft Java 1.21.11; DO NOT EDIT.\npackage server\n\nimport \"github.com/coalaura/minicraft/internal/game\"\n\nvar naturalBiomeSpawns = [game.BiomeCount][naturalCategoryCount][]naturalSpawnEntry{\n")

	categories := []string{"monster", "creature", "ambient", "water_ambient"}

	for _, name := range game.BiomeNames {
		contents, err := os.ReadFile(filepath.Join(*input, name+".json"))
		must(err)

		var biome biomeData

		must(json.Unmarshal(contents, &biome))

		fmt.Fprintf(&buffer, "game.Biome%s: {\n", identifier(name))

		for categoryIndex, category := range categories {
			fmt.Fprintf(&buffer, "%d: {\n", categoryIndex)

			for _, entry := range biome.Spawners[category] {
				typeName := strings.TrimPrefix(entry.Type, "minecraft:")
				if !supported[typeName] {
					continue
				}

				cost := biome.Costs[entry.Type]

				fmt.Fprintf(&buffer, "{Type: game.Entity%s, Weight: %d, Minimum: %d, Maximum: %d, Charge: %g, Budget: %g},\n", identifier(typeName), entry.Weight, entry.Minimum, entry.Maximum, cost.Charge, cost.Budget)
			}

			buffer.WriteString("},\n")
		}

		buffer.WriteString("},\n")
	}

	buffer.WriteString("}\n")

	biomeTags := []string{"spawns_warm_variant_farm_animals", "spawns_cold_variant_farm_animals", "allows_tropical_fish_spawns_at_any_height"}
	variables := []string{"naturalWarmFarmBiomes", "naturalColdFarmBiomes", "naturalTropicalAnyHeightBiomes"}

	for index, name := range biomeTags {
		members := make(map[string]bool, len(game.BiomeNames))

		resolveBiomeTag(*tags, name, members, make(map[string]bool))

		fmt.Fprintf(&buffer, "\nvar %s = [game.BiomeCount]bool{\n", variables[index])

		for _, biome := range game.BiomeNames {
			if members[biome] {
				fmt.Fprintf(&buffer, "game.Biome%s: true,\n", identifier(biome))
			}
		}

		buffer.WriteString("}\n")
	}

	formatted, err := format.Source(buffer.Bytes())
	must(err)

	must(os.WriteFile(*output, formatted, 0o644))
}

func resolveBiomeTag(directory string, name string, members map[string]bool, visiting map[string]bool) {
	if visiting[name] {
		panic("cyclic biome tag: " + name)
	}

	visiting[name] = true

	contents, err := os.ReadFile(filepath.Join(directory, name+".json"))
	must(err)

	var tag biomeTag

	must(json.Unmarshal(contents, &tag))

	for _, value := range tag.Values {
		if strings.HasPrefix(value, "#") {
			resolveBiomeTag(directory, strings.TrimPrefix(value[1:], "minecraft:"), members, visiting)
		} else {
			members[strings.TrimPrefix(value, "minecraft:")] = true
		}
	}

	delete(visiting, name)
}

func identifier(name string) string {
	var buffer strings.Builder

	buffer.Grow(len(name))

	for part := range strings.SplitSeq(name, "_") {
		buffer.WriteString(strings.ToUpper(part[:1]))
		buffer.WriteString(part[1:])
	}

	return buffer.String()
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
