package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode"
)

type ItemDefinition struct {
	ID        uint16 `json:"id"`
	Name      string `json:"name"`
	StackSize int32  `json:"stackSize"`
}

type BlockProperty struct {
	Name   string   `json:"name"`
	Values []string `json:"values"`
}

type BlockDefinition struct {
	Name         string          `json:"name"`
	DefaultState uint16          `json:"defaultState"`
	Properties   []BlockProperty `json:"states"`
	BoundingBox  string          `json:"boundingBox"`
}

type PlaceableBlock struct {
	Definition BlockDefinition
	Rule       string
}

func main() {
	itemsPath := flag.String("items", "", "path to items.json")
	blocksPath := flag.String("blocks", "", "path to blocks.json")
	outputPath := flag.String("output", "", "generated Go output path")

	flag.Parse()

	if *itemsPath == "" || *blocksPath == "" || *outputPath == "" {
		fmt.Fprintln(os.Stderr, "items, blocks and output are required")

		os.Exit(2)
	}

	items, err := readItems(*itemsPath)
	if err != nil {
		fail(err)
	}

	blocks, err := readBlocks(*blocksPath)
	if err != nil {
		fail(err)
	}

	generated, err := generate(items, blocks)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*outputPath, generated, 0o644)
	if err != nil {
		fail(err)
	}
}

func readItems(path string) ([]ItemDefinition, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var items []ItemDefinition

	err = json.Unmarshal(raw, &items)
	return items, err
}

func readBlocks(path string) ([]BlockDefinition, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var blocks []BlockDefinition

	err = json.Unmarshal(raw, &blocks)
	return blocks, err
}

func generate(items []ItemDefinition, blocks []BlockDefinition) ([]byte, error) {
	if len(items) == 0 {
		return nil, fmt.Errorf("item catalogue is empty")
	}

	for index, item := range items {
		if int(item.ID) != index {
			return nil, fmt.Errorf("item ID %d at index %d is not contiguous", item.ID, index)
		}
	}

	placeableBlocks := make(map[string]PlaceableBlock)

	for _, block := range blocks {
		rule := blockPlacementRule(block)
		if block.DefaultState == 0 || rule == "" {
			continue
		}

		placeableBlocks[block.Name] = PlaceableBlock{Definition: block, Rule: rule}
	}

	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-items; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package game")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "const MaxItemID Item = %d\n\n", items[len(items)-1].ID)
	fmt.Fprintln(&output, "const (")

	for _, item := range items {
		fmt.Fprintf(&output, "\tItem%s Item = %d\n", goName(item.Name), item.ID)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var itemDefinitions = [...]ItemDefinition{")

	for _, item := range items {
		fmt.Fprintf(
			&output,
			"\t{ID: Item%s, Name: %q, StackSize: %d},\n",
			goName(item.Name),
			item.Name,
			item.StackSize,
		)
	}

	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var itemPlacementBlocks = [MaxItemID + 1]Block{")

	for _, item := range items {
		block, ok := placeableBlocks[item.Name]
		if !ok {
			continue
		}

		fmt.Fprintf(&output, "\tItem%s: %s,\n", goName(item.Name), goName(block.Definition.Name))
	}

	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var itemPlacementRules = [MaxItemID + 1]ItemPlacementRule{")

	for _, item := range items {
		block, ok := placeableBlocks[item.Name]
		if !ok {
			continue
		}

		fmt.Fprintf(&output, "\tItem%s: %s,\n", goName(item.Name), block.Rule)
	}

	fmt.Fprintln(&output, "}")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return formatted, nil
}

func blockPlacementRule(block BlockDefinition) string {
	switch {
	case block.Name == "barrel":
		return "ItemPlacementDirectionalFacing"
	case block.Name == "chest" || block.Name == "trapped_chest" || isCopperChest(block.Name):
		return "ItemPlacementChest"
	case isExcludedPlacementBlock(block.Name):
		return ""
	case strings.HasSuffix(block.Name, "_slab"):
		return "ItemPlacementSlab"
	case strings.HasSuffix(block.Name, "_stairs"):
		return "ItemPlacementStairs"
	case strings.HasSuffix(block.Name, "_trapdoor"):
		return "ItemPlacementTrapdoor"
	case strings.HasSuffix(block.Name, "_door"):
		return "ItemPlacementDoor"
	case strings.HasSuffix(block.Name, "_fence_gate"):
		return "ItemPlacementFenceGate"
	case strings.HasSuffix(block.Name, "_fence"):
		return "ItemPlacementFence"
	case block.Name == "iron_bars" || strings.HasSuffix(block.Name, "copper_bars") || strings.HasSuffix(block.Name, "_glass_pane") || block.Name == "glass_pane":
		return "ItemPlacementPane"
	case strings.HasSuffix(block.Name, "_wall"):
		return "ItemPlacementWall"
	case strings.HasSuffix(block.Name, "_leaves"):
		return "ItemPlacementLeaves"
	case strings.HasSuffix(block.Name, "_chain"):
		return "ItemPlacementChain"
	case isSimpleCarpet(block.Name):
		return "ItemPlacementSupported"
	case strings.HasSuffix(block.Name, "_button"):
		return "ItemPlacementButton"
	case strings.HasSuffix(block.Name, "_pressure_plate"):
		if hasProperty(block.Properties, "power") {
			return "ItemPlacementWeightedPressurePlate"
		}

		return "ItemPlacementPressurePlate"
	case block.Name == "snow":
		return "ItemPlacementSnow"
	case block.Name == "candle" || strings.HasSuffix(block.Name, "_candle"):
		return "ItemPlacementCandle"
	case block.Name == "pointed_dripstone":
		return "ItemPlacementPointedDripstone"
	case block.Name == "furnace" || block.Name == "smoker" || block.Name == "blast_furnace":
		return "ItemPlacementFurnace"
	case isSimplePlant(block.Name):
		return "ItemPlacementPlant"
	case block.Name == "cobweb":
		return "ItemPlacementDefault"
	case isMushroomBlock(block.Name) && hasOnlyProperties(block.Properties, "down", "east", "north", "south", "up", "west"):
		return "ItemPlacementDefault"
	case hasOnlyProperties(block.Properties, "snowy"):
		return "ItemPlacementDefault"
	case isCopperGrate(block.Name) && hasOnlyProperties(block.Properties, "waterlogged"):
		return "ItemPlacementDefault"
	}

	if len(block.Properties) == 0 && block.BoundingBox == "block" {
		return "ItemPlacementDefault"
	}

	if horizontalFacingProperties(block.Properties) {
		return "ItemPlacementHorizontalFacing"
	}

	if len(block.Properties) != 1 {
		return ""
	}

	property := block.Properties[0]
	if property.Name != "axis" || len(property.Values) != 3 {
		return ""
	}

	if property.Values[0] != "x" || property.Values[1] != "y" || property.Values[2] != "z" {
		return ""
	}

	return "ItemPlacementAxis"
}

func isExcludedPlacementBlock(name string) bool {
	switch name {
	case "beacon", "beehive", "bee_nest", "brewing_stand",
		"campfire", "soul_campfire", "suspicious_gravel", "suspicious_sand",
		"chiseled_bookshelf", "crafter", "decorated_pot", "dispenser", "dropper",
		"enchanting_table", "ender_chest", "hopper", "jukebox", "lectern",
		"spawner", "trial_spawner", "vault":
		return true
	}

	return strings.HasSuffix(name, "_bed") || strings.HasSuffix(name, "_banner") ||
		strings.HasSuffix(name, "_chest") || strings.HasSuffix(name, "_shulker_box") ||
		strings.HasSuffix(name, "_shelf") || strings.HasSuffix(name, "_sign") || strings.HasSuffix(name, "_hanging_sign")
}

func isCopperGrate(name string) bool {
	return name == "copper_grate" || strings.HasSuffix(name, "_copper_grate")
}

func isCopperChest(name string) bool {
	return name == "copper_chest" || strings.HasSuffix(name, "_copper_chest")
}

func isSimplePlant(name string) bool {
	switch name {
	case "short_grass", "fern", "dead_bush", "bush", "short_dry_grass", "tall_dry_grass",
		"dandelion", "poppy", "blue_orchid", "allium", "azure_bluet", "red_tulip",
		"orange_tulip", "white_tulip", "pink_tulip", "oxeye_daisy", "cornflower",
		"wither_rose", "lily_of_the_valley", "open_eyeblossom", "closed_eyeblossom",
		"firefly_bush":
		return true
	default:
		return false
	}
}

func isMushroomBlock(name string) bool {
	return name == "brown_mushroom_block" || name == "red_mushroom_block" || name == "mushroom_stem"
}

func isSimpleCarpet(name string) bool {
	return name != "pale_moss_carpet" && (name == "moss_carpet" || strings.HasSuffix(name, "_carpet"))
}

func hasOnlyProperties(properties []BlockProperty, names ...string) bool {
	if len(properties) != len(names) {
		return false
	}

	for index, name := range names {
		if properties[index].Name != name {
			return false
		}
	}

	return true
}

func hasProperty(properties []BlockProperty, name string) bool {
	for _, property := range properties {
		if property.Name == name {
			return true
		}
	}

	return false
}

func horizontalFacingProperties(properties []BlockProperty) bool {
	if len(properties) != 1 || properties[0].Name != "facing" {
		return false
	}

	values := properties[0].Values
	return len(values) == 4 && values[0] == "north" && values[1] == "south" && values[2] == "west" && values[3] == "east"
}

func goName(name string) string {
	parts := strings.Split(name, "_")

	for index, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}

		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}

	return strings.Join(parts, "")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)

	os.Exit(1)
}
