package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode"
)

// expectedBiomeCount is the 1.21.11 catalogue size. Update it intentionally
// when upgrading the pinned biome reference data.
const expectedBiomeCount = 65

type biomeDefinition struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func main() {
	inputPath := flag.String("input", "", "path to biomes.json")
	gameOutputPath := flag.String("game-output", "", "generated game Go output path")
	protocolOutputPath := flag.String("protocol-output", "", "generated protocol Go output path")

	flag.Parse()

	if *inputPath == "" || *gameOutputPath == "" || *protocolOutputPath == "" {
		fmt.Fprintln(os.Stderr, "input, game-output and protocol-output are required")

		os.Exit(2)
	}

	raw, err := os.ReadFile(*inputPath)
	if err != nil {
		fail(err)
	}

	var biomes []biomeDefinition

	err = json.Unmarshal(raw, &biomes)
	if err != nil {
		fail(err)
	}

	err = validate(biomes)
	if err != nil {
		fail(err)
	}

	gameOutput, err := generateGame(biomes)
	if err != nil {
		fail(err)
	}

	protocolOutput, err := generateProtocol(biomes)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*gameOutputPath, gameOutput, 0o644)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*protocolOutputPath, protocolOutput, 0o644)
	if err != nil {
		fail(err)
	}
}

func validate(biomes []biomeDefinition) error {
	if len(biomes) != expectedBiomeCount {
		return fmt.Errorf("biome catalogue has %d entries, want %d", len(biomes), expectedBiomeCount)
	}

	names := make(map[string]struct{}, len(biomes))
	constantNames := make(map[string]struct{}, len(biomes))

	for index, biome := range biomes {
		if biome.ID != index {
			return fmt.Errorf("biome ID %d at index %d is not contiguous", biome.ID, index)
		}

		if biome.ID > 255 {
			return fmt.Errorf("biome ID %d does not fit uint8", biome.ID)
		}

		if biome.Name == "" {
			return fmt.Errorf("biome at index %d has an empty name", index)
		}

		if _, exists := names[biome.Name]; exists {
			return fmt.Errorf("biome name %q is duplicated", biome.Name)
		}

		names[biome.Name] = struct{}{}

		constantName := "Biome" + goName(biome.Name)
		if _, exists := constantNames[constantName]; exists {
			return fmt.Errorf("biome name %q duplicates generated constant %s", biome.Name, constantName)
		}

		constantNames[constantName] = struct{}{}
	}

	return nil
}

func generateGame(biomes []biomeDefinition) ([]byte, error) {
	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-biomes; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package game")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "const (")

	for _, biome := range biomes {
		fmt.Fprintf(&output, "\tBiome%s Biome = %d\n", goName(biome.Name), biome.ID)
	}

	fmt.Fprintf(&output, "\n\tBiomeCount Biome = %d\n", len(biomes))
	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var BiomeNames = [...]string{")

	for _, biome := range biomes {
		fmt.Fprintf(&output, "\t%q,\n", biome.Name)
	}

	fmt.Fprintln(&output, "}")

	return formatGenerated(output.Bytes())
}

func generateProtocol(biomes []biomeDefinition) ([]byte, error) {
	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-biomes; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package protocol")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var biomeRegistryEntries = []string{")

	for _, biome := range biomes {
		fmt.Fprintf(&output, "\t%q,\n", "minecraft:"+biome.Name)
	}

	fmt.Fprintln(&output, "}")

	return formatGenerated(output.Bytes())
}

func formatGenerated(source []byte) ([]byte, error) {
	formatted, err := format.Source(source)
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return formatted, nil
}

func goName(name string) string {
	parts := strings.Split(name, "_")

	for index, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}

		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}

	return strings.Join(parts, "")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)

	os.Exit(1)
}
