package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode"
)

const expectedEntityCount = 157

type entityDefinition struct {
	ID         int     `json:"id"`
	InternalID int     `json:"internalId"`
	Name       string  `json:"name"`
	Width      float64 `json:"width"`
	Height     float64 `json:"height"`
}

func main() {
	inputPath := flag.String("input", "", "path to entities.json")
	outputPath := flag.String("output", "", "generated game Go output path")

	flag.Parse()

	if *inputPath == "" || *outputPath == "" {
		fail(fmt.Errorf("input and output are required"))
	}

	definitions, err := readDefinitions(*inputPath)
	if err != nil {
		fail(err)
	}

	generated, err := generate(definitions)
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(*outputPath, generated, 0o644)
	if err != nil {
		fail(err)
	}
}

func readDefinitions(path string) ([]entityDefinition, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var definitions []entityDefinition

	err = json.Unmarshal(raw, &definitions)
	return definitions, err
}

func generate(definitions []entityDefinition) ([]byte, error) {
	err := validate(definitions)
	if err != nil {
		return nil, err
	}

	var output bytes.Buffer

	fmt.Fprintln(&output, "// Code generated by cmd/generate-entities; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package game")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "const MaxEntityType EntityType = %d\n\n", definitions[len(definitions)-1].ID)
	fmt.Fprintln(&output, "const (")

	for _, definition := range definitions {
		fmt.Fprintf(&output, "\tEntity%s EntityType = %d\n", goName(definition.Name), definition.ID)
	}

	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var entityDefinitions = [...]EntityDefinition{")

	for _, definition := range definitions {
		fmt.Fprintf(&output, "\t{ID: Entity%s, Name: %q, Width: %g, Height: %g},\n", goName(definition.Name), definition.Name, definition.Width, definition.Height)
	}

	fmt.Fprintln(&output, "}")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return formatted, nil
}

func validate(definitions []entityDefinition) error {
	if len(definitions) != expectedEntityCount {
		return fmt.Errorf("entity catalogue has %d entries, want %d", len(definitions), expectedEntityCount)
	}

	names := make(map[string]struct{}, len(definitions))
	constantNames := make(map[string]struct{}, len(definitions))

	for index, definition := range definitions {
		if definition.ID != index {
			return fmt.Errorf("entity ID %d at index %d is not contiguous", definition.ID, index)
		}

		if definition.InternalID != definition.ID {
			return fmt.Errorf("entity %q internal ID %d, want %d", definition.Name, definition.InternalID, definition.ID)
		}

		if definition.Name == "" {
			return fmt.Errorf("entity at index %d has an empty name", index)
		}

		if definition.Width < 0 || definition.Height < 0 {
			return fmt.Errorf("entity %q has invalid dimensions %g x %g", definition.Name, definition.Width, definition.Height)
		}

		if _, exists := names[definition.Name]; exists {
			return fmt.Errorf("entity name %q is duplicated", definition.Name)
		}

		names[definition.Name] = struct{}{}

		constantName := "Entity" + goName(definition.Name)
		if _, exists := constantNames[constantName]; exists {
			return fmt.Errorf("entity name %q duplicates generated constant %s", definition.Name, constantName)
		}

		constantNames[constantName] = struct{}{}
	}

	return nil
}

func goName(name string) string {
	parts := strings.Split(name, "_")

	for index, part := range parts {
		runes := []rune(part)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
			parts[index] = string(runes)
		}
	}

	return strings.Join(parts, "")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
